### ISSUE TITLE
Missing version definations

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-cli#101]
Some of the dependent gems did not include the `version` file by default, so when we try to display the versions then it throws some here.

<img width="706" alt="Screenshot 2019-07-19 12 00 18" src="https://user-images.githubusercontent.com/1220911/61527539-fbb10780-aa1c-11e9-9c52-5b49dafc576c.png">

@opoudjis: was it something we did for some reason or should we just go ahead and include those on those gems?

**Comment by ronaldtse** [comment]
@abunashir all gems are supposed to have the VERSION constant. Could you help fix them? Thanks.

**Comment by opoudjis** [comment]
That is a surprise. Let me look at these.

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-acme/blob/master/lib/metanorma/acme/version.rb defines Metanorma::Acme::VERSION. But it looks like I forgot to include the version.rb file in the parent ruby file. Fixing.

**Comment by opoudjis** [comment]
Omission I can't really account for. Resolved.

**Comment by ronaldtse** [comment]
@opoudjis OGC is also missing the version. Has that been fixed? Thanks.

**Comment by ronaldtse** [comment]
Aha it was done here: https://github.com/metanorma/metanorma-ogc/pull/39 . Thanks guys!

**Comment by abunashir** [comment]
Perfect, thanks a lot @opoudjis!
