### ISSUE TITLE
metanorma local templates didn't handle symlinks correctly

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#103]
`metanorma new test/$template --type $TYPE --doctype $template --template . --overwrite` didn't handle symlinks correctly

Examples:
 - https://travis-ci.com/metanorma/mn-templates-ietf/jobs/213835475
 - https://travis-ci.com/metanorma/mpfd-documents/builds/120146974

**Comment by ronaldtse** [comment]
Ping @abunashir -- can you help with this? Thanks.

**Comment by abunashir** [comment]
@CAMOBAP795: Are you working on this one?

**Comment by CAMOBAP795** [comment]
@abunashir not yet, I just found it

**Comment by abunashir** [comment]
Cool, I will un-assign myself then!

**Comment by CAMOBAP** [comment]
looks like not a case anymore, need to be doublechecked
