### ISSUE TITLE
Missing dependent backends

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-cli#104]
There are some missing backends in our gem specs, looking at the commit message it might have some to do with enterprise gems, @opoudjis could you confirm?

<img width="681" alt="Screenshot 2019-08-01 16 03 43" src="https://user-images.githubusercontent.com/1220911/62299933-32a00800-b476-11e9-82bd-35312fb938ae.png">

**Comment by ronaldtse** [comment]
@abunashir yes this is correct. The enterprise gems should not be "default" but the CLI should be able to detect them if they are installed. If the enterprise gems are not installed, the lack of them should not cause any warning message.

**Comment by opoudjis** [comment]
In fact, @abunashir, Ronald explicitly asked me to take those gems out of a previous iteration of Metanorma. 

I'll assign the ticket back to you for @ronaldtse's requested resolution.

**Comment by abunashir** [comment]
@ronaldtse: I've added a temporary fix, for now, it will silently ignore loading issue for this private gems. in the future, we also consider having those as configuration block.
