### ISSUE TITLE
Latexml issue for the test suite

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-cli#109]
Hey there, we might have introduced some issue with our recent changes in `metanorma-standoc`, specifically after version `1.2.2`. Now our test suite seems to be throwing some error about missing `latexml `. log: https://travis-ci.org/metanorma/metanorma-cli/jobs/570490119#L832

<img width="1079" alt="Screen Shot 2019-08-11 at 4 39 04 PM" src="https://user-images.githubusercontent.com/1220911/62835286-faa77a80-bc56-11e9-83cd-0c2da3b4629c.png">

Do we need to tweak something in our Travis build, is it something we can fix on the `metanorma-standoc?`.

cc: @opoudjis, @CAMOBAP795, @ronaldtse

**Comment by CAMOBAP795** [comment]
Here is PR to fix this https://github.com/metanorma/metanorma-standoc/pull/98

**Comment by abunashir** [comment]
@CAMOBAP795: Are we good with this one? Can we close this issue now?

**Comment by CAMOBAP795** [comment]
@abunashir I think we can close it because PR merged already
