### ISSUE TITLE
URGENT: `Metanorma::Cli::Errors::FileNotFoundError` hiding ALL unrelated errors

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#115]
Many file related errors are not `FileNotFound` errors.

Right now, there is no way to show the debug messages or actual error traces that caused the failure.

This task is to expose actual errors or at least provide a message + a method on how to show the debug messages/actual errors.

compiler.rb:
And here we lost ALL error and backtrace information by throwing a new error without context.
<img width="400" alt="Screen Shot 2019-09-09 at 12 55 53 PM" src="https://user-images.githubusercontent.com/11865/64504227-2a52ac80-d301-11e9-8313-7049881aecb9.png">

**Comment by ronaldtse** [comment]
I found out the "missing image" error will trigger this. This is completely unacceptable.

```
Errno::ENOENT: No such file or directory @ rb_sysopen - sources/images/figure1.png
```

This is the original error. There is no mention of this cause during compilation. Clearly the error cannot be solved by the message "Not sure what to run? See `metanorma help`".

Ping @abunashir

**Comment by CAMOBAP795** [comment]
@ronaldtse just to be on the same page expected result is to:
 - ~"Not sure what to run? See metanorma help"~
 - re-throw original error

Also, I think that if we will include the line of code where error happens, that will be very usefull for end-users

How do you think?

**Comment by ronaldtse** [comment]
I think the original error message was meant to be shown for the case when the user put in a missing file on the command line. But it is overzealous in catching ENOENT. It should only catch ENOENT of the SINGLE file.

**Comment by CAMOBAP795** [comment]
@ronaldtse got your point, what is expected behavior for handling missing files which were referred from `*.adoc` files?

**Comment by ronaldtse** [comment]
@CAMOBAP795 :

* missing the input file directly (i.e. `metanorma compile {missing-file.adoc}`)' => raise error of file not found, explain to the user that the file is not found.
* any other error (including: missing image file, missing included doc file), write out a message that an error has occurred, if you want to see the full trace, use `--trace` option.

**Comment by abunashir** [comment]
Sorry, I overlooked this one. @CAMOBAP795: Are you working on it?

**Comment by ronaldtse** [comment]
I've just commented out this error catching code for sanity in new releases. This feature has to be implemented properly.

**Comment by CAMOBAP795** [comment]
@ronaldtse I suppose make sense to keep it open, right?

**Comment by ronaldtse** [comment]
I've already fixed the issue.
