### ISSUE TITLE
Unclear how to install PlantUML for Metanorma under Ubuntu Linux

### ISSUE THREAD

**Issue by strogonoff** [metanorma/metanorma-cli#118]
[Installation guide here](https://www.metanorma.com/software/metanorma-cli/docs/installation/#plantuml) ([source](https://github.com/metanorma/metanorma-cli/blob/master/docs/installation.adoc#plantuml)) gives a one-liner for PlantUML installation on macOS, but for Linux it refers to `.travis.yml`.

Which `.travis.yml` is meant?

Perhaps the docs could link it? I can make a PR to add the link, but I need a pointer to the right `.travis.yml`.

**Comment by ronaldtse** [comment]
@strogonoff the PlantUML installation script for Ubuntu is this:

https://github.com/metanorma/plantuml-install/blob/master/ubuntu.sh

**Comment by ronaldtse** [comment]
Closing this for now.
