### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#121]
Remove Travis and AppVeyor.

**Comment by opoudjis** [comment]
Reminder to do this; I need this for the dashboard for gem updates.

**Comment by ronaldtse** [comment]
@CAMOBAP795 ping again

**Comment by CAMOBAP795** [comment]
https://github.community/t5/GitHub-Actions/Triggering-by-other-repository/td-p/30668

**Comment by ronaldtse** [comment]
Done in #127 . Closing.
