### ISSUE TITLE
Metanorma-CSAND appears twice in `metanorma version`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#122]
Self explanatory output: (this is with the latest metanorma CLI)

```sh
$ bundle exec metanorma version 
Metanorma 0.3.15
Metanorma::Cli 1.2.7
nil versions are discouraged and will be deprecated in Rubygems 4
Metanorma::Standoc 1.3.4/IsoDoc 1.0.4
Metanorma::ISO 1.3.4
Metanorma::Iec 0.0.7
Metanorma::Ietf 1.0.6
Metanorma::Gb 1.3.4
Metanorma::Csd 1.3.3
Metanorma::Csand 1.3.3 <<<=====
Metanorma::Csand 1.3.3
Metanorma::M3d 1.3.3
Metanorma::Acme 1.3.3
Metanorma::Unece 0.2.4
Metanorma::NIST 0.2.4
Metanorma::Ogc 0.2.4
Metanorma::ITU 0.2.6
```

**Comment by andrew2net** [comment]
@ronaldtse do you relay want to assign it to me?

**Comment by abunashir** [comment]
Just to add to this existing issue - the current executable is throwing out the following error:

<img width="675" alt="Screen Shot 2020-01-31 at 1 34 22 PM" src="https://user-images.githubusercontent.com/1220911/73539925-df137480-442e-11ea-9be9-3661798e684e.png">

**Comment by ronaldtse** [comment]
It has been renamed to “metanorma-csa”. Could you help fix it? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse @abunashir I can help

**Comment by ronaldtse** [comment]
Please help then. Thanks!

**Comment by opoudjis** [comment]
This issue has been resolved.
