### ISSUE TITLE
URGENT: GHA trigger failing due to missing parameters

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#128]
Is there any existing GitHub Actions that we can re-use here?

<img width="788" alt="image" src="https://user-images.githubusercontent.com/11865/73601233-97106100-4598-11ea-90fd-d2203d933173.png">

**Comment by CAMOBAP795** [comment]
@ronaldtse I have no access to settings of this project so I cannot add a secure variable:
 - PAT_USERNAME - GitHub user id (maybe we have special GH user to trigger build)
 - PAT_TOKEN - Personal Access Token - https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line

**Comment by ronaldtse** [comment]
I've added the secrets, let's see if it works...
