### ISSUE TITLE
Add NISO STS / ISOSTS output via mn2sts

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#142]
mn2sts is a Java program that converts Metanorma XML into NISO STS XML output.

This task is to integrate the `sts.xml` output format for Metanorma-ISO and Metanorma-IEC.

The gem `mn2sts` is available from https://github.com/metanorma/mn2sts-ruby

**Comment by opoudjis** [comment]
Duplicates https://github.com/metanorma/metanorma-iso/issues/386

Assigning me the same ticket twice is not going to reduce the backlog getting in the way of me doing it, @ronaldtse
