### ISSUE TITLE
dispatch_repository broken on release 

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#144]
https://github.com/metanorma/metanorma-cli/runs/749732886?check_suite_focus=true#step:6:1

```
Trigger repository_dispatch for metanorma/metanorma-docker with { "event_type": "metanorma/metanorma-cli", "client_payload": { "ref": "refs/heads/master" }} } client_payload={ "ref": "refs/heads/master" }} client_payload2={ "ref": "refs/heads/master" }}
{
  "message": "Problems parsing JSON",
  "documentation_url": "https://developer.github.com/v3"
}
```

Two problems here:
 - dispatch_repository problem with payload
 - dispatch_repository not triggered for tags

**Comment by CAMOBAP** [comment]
Code pushed but I cannot release because 

`You do not have permission to push to this gem. Ask an owner to add you with: gem owner metanorma-cli --add abobrikovich@gmail.com`

I need a new release (1.2.13.1) to trigger other repos build

@opoudjis @ronaldtse can someone allow me to release

**Comment by ronaldtse** [comment]
Done!

**Comment by CAMOBAP** [comment]
Repos below wasn't triggered by some reason
 - packed-mn
 - chocolatey-metanorma

Investigating

**Comment by ronaldtse** [comment]
@CAMOBAP 

packed-mn failed:

```
Run failed for master (4ddaacc)

Repository: metanorma/packed-mn
Workflow: release-tag
Duration: 26.0 seconds
Finished: 2020-06-08 20:09:48 UTC

View results

Jobs:
push-tag failed (1 annotation)
```

**Comment by CAMOBAP** [comment]
Right regarding `packed-mn`, https://github.com/metanorma/packed-mn/runs/751399100?check_suite_focus=true I will check it

For `chocolatey-metanorma` it report 
```
Trigger repository_dispatch for metanorma/chocolatey-metanorma with { "event_type": "metanorma/metanorma-cli", "client_payload": { "ref": "refs/tags/v1.2.13.1" } } client_payload={ "ref": "refs/tags/v1.2.13.1" }
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

Maybe it's related to missing `secrets.PAT_TOKEN`. 

@ronaldtse as far as I remember we added `secrets.METANORMA_CI_PAT_TOKEN` to our repos also, `secrets.PAT_TOKEN` and `secrets.METANORMA_CI_PAT_TOKEN` should be the same right?

**Comment by CAMOBAP** [comment]
Investigation/work will be continued in:
 - https://github.com/metanorma/chocolatey-metanorma/issues/47
 - https://github.com/metanorma/packed-mn/issues/27
