### ISSUE TITLE
Windows tests are broken

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#147]
Reason 100% the same as for https://github.com/relaton/relaton-cli/issues/79

Action items:
 - [x] move to `` or `Open3.capture3` API for command execution
 - [x] Prepare minimal reproducible code snipped to report the issue to external component

**Comment by CAMOBAP** [comment]
https://github.com/chef/win32-process/issues/30 - reported

**Comment by ronaldtse** [comment]
@CAMOBAP is this fixed? Thanks.

**Comment by CAMOBAP** [comment]
Yep, it's done
