### ISSUE TITLE
Trigger mn-templates-* mn-samples-* tests

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#149]
@opoudjis @ronaldtse I need your opinion, to me, it looks like we need to trigger it for each push to master not just for release flow.

Make sense?

**Comment by ronaldtse** [comment]
@CAMOBAP Yes, we should trigger mn-{samples, templates}-* tests in `metanorma-cli` repo for all pushes to master and PRs. Thanks!

**Comment by opoudjis** [comment]
And as discussed yesterday, for each template:

* Extract the bibdata element to a text file
* Compare the currently generated document's bibdata element to that text file:

````
expect(xmlpp(strip_guid(Nokogiri::XML(File.read("document.xml", encoding: "utf-8"))).at("//xmlns::bibdata).to_xml)).to be_equivalent_to xmlpp(strip_guid(File.read("bibdata.xml", encoding: "utf-8")))
````

For definitions of xmlpp and strip_guid, see any metanorma flavour spec_helper:

````
def strip_guid(x)
  x.gsub(%r{ id="_[^"]+"}, ' id="_"').gsub(%r{ target="_[^"]+"}, ' target="_"')
end


def xmlpp(x)
  s = ""
  f = REXML::Formatters::Pretty.new(2)
  f.compact = true
  f.write(REXML::Document.new(x),s)
  s
end

````

**Comment by CAMOBAP** [comment]
Done for templates 
 - https://github.com/metanorma/metanorma-cli/pull/new/feature/trigger-templates

For mn-samples-* I need a think a bit how to implement it better (there is several approach how it can be done)

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis btw how do you think if we will run tests samples/templates on change of respective metanorma processor? It sounds reasonable to me

**Comment by ronaldtse** [comment]
@opoudjis can we *not* use REXML?

**Comment by ronaldtse** [comment]
> btw how do you think if we will run tests samples/templates on change of respective metanorma processor? It sounds reasonable to me

Yes please, thanks.

**Comment by opoudjis** [comment]
> @opoudjis can we *not* use REXML?

@ronaldtse ... why?

I'm using it so that the XML outputs of rspec line up. There is no functionality issue here. It's working.

**Comment by CAMOBAP** [comment]
Triggering by itself works, but we have some issues on workflows on templates/samples side, I will  investigate it in the scope of this task

**Comment by CAMOBAP** [comment]
@ronaldtse I have no write access to:
 - https://github.com/metanorma/mn-templates-un
 - https://github.com/metanorma/mn-templates-m3aawg
Could you please add me to allow configuration update

**Comment by CAMOBAP** [comment]
Done

**Comment by ronaldtse** [comment]
@CAMOBAP fixed access to those two repos. Thanks!
