### ISSUE TITLE
Test failing test suite

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#154]
@andrew2net: This was failing the test suite, I'm skipping this one for the PR, but could you please have a look into this afterword and create a new PR if necessary?

_Originally posted by @abunashir in https://github.com/metanorma/metanorma-cli/pull/143_

**Comment by andrew2net** [comment]
@ronaldtse I don't see any test failing. Can we close this issue?

**Comment by ronaldtse** [comment]
Fantastic. Thanks!
