### ISSUE TITLE
`metanorma setup` seems to provide garbled output?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#158]
From @TRThurman :

It's showing:
> garbled license for fonts.

> then this:
```

acceptance of the font licenses, type "Yes" / "No": Yes
/var/folders/w9/c20j6z453kgcpmwbh3zmfzrm0000gn/T/d20200706-7481-1h8ef75/ppviewer.cab: WARNING; possible 5968 extra bytes at end of file.
[info]: Font `SimSun` is not supported yet!
[info]: Font `SimHei` is not supported yet!
[info]: Font `AzoSans` is not supported yet!
[info]: Font `AzoSans-Light` is not supported yet!
Metanorma has detected that you do not have the necessary fonts installed
for PDF generation. The generated PDF will use generic fonts that may not
semble the desired styling. Metanorma can download these files for you
if you accept the font licensing conditions for the font Overpass.

Yes

ese fonts for you and indicate yourh 
acceptance of the font licenses, type "Yes" / "No": Yes
[info]: Font `Space Mono` is not supported yet!
[info]: Font `Garamond` is not supported yet!

```

**Comment by ronaldtse** [comment]
@abunashir I wonder why this is happening. I believe this is for Catalina. I've never encountered this, though. Garbled text can either be due to shell issues or parallel processing, which I don't think is happening here?

**Comment by abunashir** [comment]
I'm not sure either, we're not doing any parallel processing for installation but I will double-check with my device that's running Catalina.

**Comment by abunashir** [comment]
@ronaldtse: Unfortunately I could not reproduce this in any of my devise, @TRThurman: Do you still face this issue with the latest version?

**Comment by TRThurman** [comment]
This is my version.
How do I update:
Metanorma 1.0.5
Metanorma::Cli 1.2.11
nil versions are discouraged and will be deprecated in Rubygems 4
Metanorma::Standoc 1.3.28/IsoDoc 1.0.26
Metanorma::ISO 1.3.24
Metanorma::Iec 1.0.6
Metanorma::Ietf 2.0.10
Metanorma::Gb 1.3.23
Metanorma::Csd 1.3.21
Metanorma::Csa 1.4.10
Metanorma::M3d 1.3.19
Metanorma::Generic 1.4.8
Metanorma::UN 0.3.8
Metanorma::NIST 1.0.7
Metanorma::Ogc 1.0.6
Metanorma::ITU 1.0.15

**Comment by TRThurman** [comment]
I found it.
brew tap metanorma/metanorma
brew install metanorma

**Comment by abunashir** [comment]
Thanks for the details @TRThurman, the local CLI version seems to be outdated and there were quite some changes since then, could you please try to run `brew update` and see if that fixes the issue?

Brew help: https://docs.brew.sh/FAQ#how-do-i-update-my-local-packages
Releases: https://github.com/metanorma/metanorma-cli/releases

**Comment by ronaldtse** [comment]
Closing for now. Thanks!
