### ISSUE TITLE
Implement `metanorma create PATH`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#16]

**Comment by opoudjis** [comment]
You will need to explain what you mean here.

**Comment by ronaldtse** [comment]
This task is to create a directory structure for creating a new Metanorma document.

For example, as in https://github.com/riboseinc/metanorma-ogc/issues/23, OGC document templates are provided here (https://github.com/opengeospatial/templates).

If a user runs `metanorma create -t ogc --doctype best-practice`, maybe we should help the user fetch the OGC best practice template. This is in line with how bundler works too.

What do you think?

ping @opoudjis @abunashir

**Comment by opoudjis** [comment]
I think that without a lot more information about directory structures --- which is simply not captured anywhere --- I cannot do this. In fact, I have *never* used a directory structure to create a Metanorma document. The OGC document template look to be a requirement idiosyncratic to OGC, and not one I'm convinced will be needed in practice.

... I think this is an idiosyncratic, OGC-specific requirement, and I am reluctant to generalise it to generic functionality. At most, when processing an OGC document, detect whether expected directories are already present, and if not, fetch them. That does not need a separate command, and users would not expect to have to remember to trigger a separate command.

**Comment by opoudjis** [comment]
Is this a duplicate of #13 ?

**Comment by ronaldtse** [comment]
Yes, it is. Closing now.
