### ISSUE TITLE
Bad testing of interactivity

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cli#164]
spec/acceptance/setup_spec.rb is not working:

In my mac, Fontist is (inaccurately) concluding that HanSans is not installed. Therefore, it attempts to download the font.

For whatever reason, downloads are getting stalled on my machine tonight; I failed to download the xalan executable in a makefile earlier tonight. So the attempt to download the font file, in fontist: lib/fontist/utils/downloader.rb, is stalling.

There needs to be provision for timeout, Fontist can't get stuck like this. And the rspec testing of setup certainly can't be permitting such downloads to happen without appropriate mocks.

I am disabling the rspec test to get the release done, but please make fontist more robust, and provide mocks in spec/acceptance/setup_spec.rb: what Fontist does to get hold of fonts should not be impacting testing of this gem.

**Comment by ronaldtse** [comment]
>In my mac, Fontist is (inaccurately) concluding that HanSans is not installed. Therefore, it attempts to download the font.

This is posted in fontist/fontist#95.

**Comment by ronaldtse** [comment]
Timeout issue posted in fontist/fontist#96.

**Comment by abunashir** [comment]
Good call to disable the tests for now, I will add some mock soon!

Regarding the stalling issue, my best guess it's related to the super slow web archive, but yes, I think we need to add some timeout option there so it doesn't try forever. I will investigate what happened there.

**Comment by abunashir** [comment]
Updated in the attached PR, let me know if there are any other issues! cc: @opoudjis, @ronaldtse

**Comment by alexeymorozov** [comment]
Hi @opoudjis. May I ask to help me reproduce the issue with HanSans?

Where is the font placed in the system, and what its name?

```ruby
Fontist::Font.find("HanSans")
# => Fontist::Errors::MissingFontError: HanSans fonts are missing, please run `fontist install 'HanSans'` to download the font.
# But it's expected to return paths, right?
```

**Comment by opoudjis** [comment]
````
~/Documents/Arbeit/upwork/ribose $ irb
2.6.6 :001 > require "fontist"
 => true 
2.6.6 :002 > Fontist::Font.find("HanSans")
Traceback (most recent call last):
        7: from /Users/nickn/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `<main>'
        6: from /Users/nickn/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `load'
        5: from /Users/nickn/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):2
        3: from /Users/nickn/.rvm/gems/ruby-2.6.6/gems/fontist-1.3.0/lib/fontist/font.rb:15:in `find'
        2: from /Users/nickn/.rvm/gems/ruby-2.6.6/gems/fontist-1.3.0/lib/fontist/font.rb:23:in `find'
        1: from /Users/nickn/.rvm/gems/ruby-2.6.6/gems/fontist-1.3.0/lib/fontist/font.rb:63:in `downloadable_font'
Fontist::Errors::MissingFontError (HanSansFonts are missing, please run Fontist::Font.install('HanSans', confirmation: 'yes') to download the font.)
````
