### ISSUE TITLE
"File not found" not failing build within metanorma build document container

### ISSUE THREAD

**Issue by Kritner** [metanorma/metanorma-cli#171]
We had [this](https://github.com/usnistgov/ACVP/issues/964) issue come in, and it took me a few minutes to realize that the "RSA" document was not showing up on our GH pages due to the RSA document "failing" to build, but not actually failing the build step.

The fix was simple enough, ensure the casing was correct between the filesystem and files "included" in our `.adoc` references.  I would have expected that this would have constituted a build failure.

Here's a snip of the build log from our github action:
![image](https://user-images.githubusercontent.com/8814983/91045619-28066280-e5e5-11ea-8dca-b8acb164dc8c.png)

And the overall disposition of the run:
![image](https://user-images.githubusercontent.com/8814983/91046035-c397d300-e5e5-11ea-8e51-65987f1aa457.png)

Once correcting the casing issue the documents were built and deployed successfully to our gh-pages branch.  I'm mostly putting this issue in because I suspect the the build should have been failing when it was not.

Here's the raw file that I would have expected to fail in the build: https://raw.githubusercontent.com/usnistgov/ACVP/master/src/draft-celi-acvp-rsa.adoc

it was a difference of referencing `siggen` as the include when `sigGen` was what was in the file system (as an example).  I don't know if this is something that can actually be hooked into since it's seemingly a ruby related error, not the building of the RFC itself.

**Comment by opoudjis** [comment]
The issue is to trigger a fail if an included document in asciidoctor does not exist. This does not get detected because of how asciidoctor preprocessing is segregated from Metanorma processing; will see if it generates rescuable error

**Comment by opoudjis** [comment]
Asciidoctor is using logger, so need to catch them from STDERR and parse them before proceeding
