### ISSUE TITLE
Build errors seeming to point to metanorma docker image

### ISSUE THREAD

**Issue by Kritner** [metanorma/metanorma-cli#172]
https://github.com/usnistgov/ACVP/runs/1103267311

![image](https://user-images.githubusercontent.com/8814983/92960208-39e86200-f43b-11ea-88bb-46c66bb4f26b.png)

Not sure if I can provide any further information, I can't say I've noticed these errors before in the build logs, usually if we get them it's related to pulling RFC documents and it pretty transient.  In this instance, that does not seem to be the case.

**Comment by ronaldtse** [comment]
@Kritner so sorry about this. We'll fix this. Apologies.

**Comment by ronaldtse** [comment]
This should be fixed in #173

**Comment by Kritner** [comment]
No problem, thanks!
