### ISSUE TITLE
Update spec.files of gemspec to not depend on `git ls-files`, include files explicitly

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#177]
Because of https://github.com/metanorma/metanorma-cli/commit/d554c9322de33ac75324470fcf9add5cf3c6fe1b

https://github.com/metanorma/homebrew-metanorma becomes broken because it downloads sources as an archive without `.git` subdirectory as result `git ls-files -z` produces empty string

Maybe you can explain what kind of limits you tried to avoid? Maybe we still have an option to build `spec.files` without `git` command

**Comment by opoudjis** [comment]
It was copy paste from past gemspecs. I think way back the gem included random scattered files outside of lib and spec, but pretty sure you can ignore that now.

**Comment by ronaldtse** [comment]
@opoudjis I think we should not use `git ls-files` for `spec.files`. This issue is still present now:

https://github.com/metanorma/metanorma-cli/blob/fded7a1c8a00cda2cb7e0fa6077b13101b3e2a79/metanorma-cli.gemspec#L22-L24

**Comment by ronaldtse** [comment]
@CAMOBAP I talked with @opoudjis and he understands the issue. Can you help update the `gemspec` so it doesn't depend on git, but includes only files that should be included? Thanks! Reopening.

**Comment by CAMOBAP** [comment]
The first approach from https://stackoverflow.com/questions/11873294/determining-the-gems-list-of-files-for-the-specification looks nice to me

**Comment by ronaldtse** [comment]
@CAMOBAP agree, can you proceed? Thanks!

**Comment by CAMOBAP** [comment]
Merged
