### ISSUE TITLE
Metanorma CLI installation issue

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-cli#202]
Hey Guys, I'm trying to install the cli locally but there there seems to be some issue regarding `rice` gem both in the master and also the latest ruby gem version. I don't see any recent update in ruby gems, Is any of the underlying dependencies has changed or is it only my machine?

Current master:

<img width="1187" alt="Screen Shot 2020-12-30 at 5 30 03 PM" src="https://user-images.githubusercontent.com/1220911/103367209-d1de8a00-4ac4-11eb-98c0-79aff3d1a402.png">

Rubygems: 

<img width="1118" alt="Screen Shot 2020-12-30 at 5 29 55 PM" src="https://user-images.githubusercontent.com/1220911/103367179-b70c1580-4ac4-11eb-9989-c7fa1c973fc0.png">

//cc: @opoudjis, @CAMOBAP, @ronaldtse

**Comment by abunashir** [comment]
Seems like CI is also reporting the similar issues - https://github.com/metanorma/metanorma-cli/pull/203/checks?check_run_id=1634040683

**Comment by ronaldtse** [comment]
This issue is related to this: https://github.com/lutaml/expressir/issues/42

The expressir gem now requires compilation, which depends on `brew install automake`. @CAMOBAP is working to get rid of this issue with precompiled gems.

**Comment by ronaldtse** [comment]
This issue is temporarily gone as I commented out support for lutaml-express (lutaml/lutaml#11). Closing.
