### ISSUE TITLE
CLI should allow building collection

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#205]
In the CLI implementation today we cannot build a metanorma collection.

This is how we do it now:
```sh
bundle exec metanorma site generate . -o published -c collection.yml
bundle exec metanorma collection si-brochure-bilingual.yml -x xml,html,presentation,pdf -w bilingual-brochure -c collection_cover.html
```

The second line builds a metanorma collection using the config file `si-brochure-bilingual.yml`.

I believe we can integrate this command into the configuration file for `site generate`. We might even want to clarify the roles of the commands: `compile`, `collection` and `site` so they have different functions.

Ping @abunashir and @CAMOBAP for thoughts.

**Comment by opoudjis** [comment]
Agreed. I would further add that the collection YAML (si-brochure-bilingual.yml) and the site YAML (collection.yml) MUST be kept separate: it would be a mistake to bind them tightly. The file name of the collection YAML should be one of the entries in the site YAML.

**Comment by ronaldtse** [comment]
Here's the relevant PR https://github.com/metanorma/bipm-si-brochure/pull/86 that we want to make working.

**Comment by abunashir** [comment]
@ronaldtse: I think this was resolved by https://github.com/metanorma/metanorma-cli/pull/260, can we close this one or is there anything else?

**Comment by abunashir** [comment]
ping @ronaldtse, @opoudjis ⬆️

**Comment by ronaldtse** [comment]
@abunashir have you updated https://github.com/metanorma/bipm-si-brochure/pull/86 to use the new functionality?

**Comment by abunashir** [comment]
Yes, I've updated the supported attributes here - https://github.com/metanorma/bipm-si-brochure/pull/86/commits/5b6d6578a88022010769721e9178167054e7ce61,  so it's there from the cli side.

For the changes on the [core attributes ](https://github.com/metanorma/bipm-si-brochure/blob/5b6d6578a88022010769721e9178167054e7ce61/sources/si-brochure-bilingual.yml#L50)we still need to do that to the metnorma itself. I can do that, but is there any concern renaming those attributes in metanorma @opoudjis?

**Comment by ronaldtse** [comment]
Thank you @abunashir ! We want to implement the changes to the inclusion attributes too:
https://github.com/metanorma/bipm-si-brochure/blob/5b6d6578a88022010769721e9178167054e7ce61/sources/si-brochure-bilingual.yml#L43-L67

Can you please help implement them in metanorma-cli? Thanks!

**Comment by ronaldtse** [comment]
@abunashir I've tried this locally and there are several problems. I will list out the problems individually.

**Comment by ronaldtse** [comment]
Let's close this issue, the remaining bugs are #283 and #284.
