### ISSUE TITLE
URGENT: Site generation not working on OGC flavor?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#215]
https://github.com/metanorma/sample-ogc-discussion-paper

```
metanorma site generate .
```

```
ls -alR site/
total 72
drwxr-xr-x   6 me  staff   192B Jan 19 03:41 ./
drwxr-xr-x  12 me  staff   384B Jan 19 03:36 ../
-rw-r--r--@  1 me  staff   6.0K Jan 19 03:41 .DS_Store
drwxr-xr-x   8 me  staff   256B Jan 19 03:40 documents/
-rw-r--r--   1 me  staff   242B Jan 19 03:40 documents.xml
-rw-r--r--   1 me  staff    20K Jan 19 03:40 index.html

site//documents:
total 7944
drwxr-xr-x  8 me  staff   256B Jan 19 03:40 ./
drwxr-xr-x  6 me  staff   192B Jan 19 03:41 ../
-rw-r--r--  1 me  staff   157K Jan 19 03:40 document.doc
-rw-r--r--  1 me  staff   8.5K Jan 19 03:39 document.err
-rw-r--r--  1 me  staff    68K Jan 19 03:40 document.html
-rw-r--r--@ 1 me  staff   2.6M Jan 19 03:40 document.pdf
-rw-r--r--  1 me  staff    61K Jan 19 03:40 document.presentation.xml
-rw-r--r--  1 me  staff    47K Jan 19 03:40 document.xml
```

But site/index.html has no document:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/11865/104957406-121c9280-5a09-11eb-95c7-3e19f9125055.png">

**Comment by abunashir** [comment]
Hey @ronaldtse, I've been looking into this, but for some reason relaton can't find any `bibitem/bibdata/rfc` node in any of the generated files to [build the collection](https://github.com/relaton/relaton-cli/blob/cb75ebb3d4f33e69f2d214589efa7818aabda44f/lib/relaton/cli/relaton_file.rb#L139), Could it be anything related to these document, or anything else you can think of?

**Comment by ronaldtse** [comment]
Looks like there is something wrong with the document generation. Adding issue to metanorma-ogc.

**Comment by ronaldtse** [comment]
But I'm seeing that the XML does contain `bibdata`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ogc-standard xmlns="https://www.metanorma.org/ns/ogc" type="semantic" version="1.2.11">
<bibdata type="standard">
<title language="en" format="text/plain">Discussion paper for OGC (add title text)</title>
<uri type="xml">./document.xml</uri>
<uri type="pdf">./document.pdf</uri>
<uri type="doc">./document.doc</uri>
<docidentifier type="ogc-external">http://www.opengis.net/doc/{doc-type}/{standard}/{m.n}</docidentifier><docidentifier type="ogc-internal">19-004</docidentifier>
...
```

**Comment by ronaldtse** [comment]
Also, Nokogiri seems to be able to read it:

```ruby
irb(main):019:0> xml.at("//bibdata").to_xml
=> "<bibdata type=\"standard\">\n<title language=\"en\"...
```

**Comment by abunashir** [comment]
I hope this should fix the issue - https://github.com/metanorma/sample-ogc-discussion-paper/pull/1, but I'm surprised that we explicitly had to specify the `rxl` for this flavour where others were working fine without even it.

**Comment by abunashir** [comment]
@ronaldtse: Can we close this one?

**Comment by ronaldtse** [comment]
Yes, thanks!
