### ISSUE TITLE
Replace hyphens here with "_" in the symbol in options but keep arguments with hyphens

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#218]
Reported: https://github.com/metanorma/metanorma-cli/pull/216#discussion_r561752560

Actually, `thor` already supports this:
 - https://github.com/erikhuda/thor/blob/34df888d721ecaa8cf0cea97d51dc6c388002742/lib/thor/parser/options.rb#L188
 - https://github.com/erikhuda/thor/issues/48

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by ronaldtse** [comment]
@CAMOBAP is this fixed and to be closed? Thanks.

**Comment by CAMOBAP** [comment]
Yep, PRs are merged, and tests passed
