### ISSUE TITLE
Installation issue with expressir, rice

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-cli#231]
Hey there, I was trying to install the cli, and noticed we are having a similar issue that was there couple of months back (build failing for expressir/rice). I can manually try to fix that for now, but I wonder if that occurs on actual user's devices and if we need to suggest anything for fix here?

<img width="1129" alt="Screenshot 2021-03-15 at 16 36 32" src="https://user-images.githubusercontent.com/1220911/111180327-3af67980-85ad-11eb-80df-e49660c92740.png">

//cc: @CAMOBAP, @ronaldtse

**Comment by abunashir** [comment]
I believe fhe first occurrence of this was around here - https://github.com/metanorma/metanorma-cli/runs/2030136038

**Comment by CAMOBAP** [comment]
Let me check, we 100% have published https://rubygems.org/gems/expressir/versions/0.2.21-x86_64-darwin platform gem for macos for both arm64 and x86_64

@abunashir what is your is version/arch, could you please print `gem env`

**Comment by CAMOBAP** [comment]
Also will `gem install expressive --platform x86_64-darwin` install prebuilt gem? Or it still fall into the same issue?

**Comment by abunashir** [comment]
I can install `expressive` but the Metanorma-cli is still seems to be failing
> Also will `gem install expressive --platform x86_64-darwin` install prebuilt gem? Or it still fall into the same issue?

**Comment by abunashir** [comment]
FYI - The latest build in the CI seems to be working fine though.

**Comment by CAMOBAP** [comment]
Sorry for the confusion, I wrongly thought that you are on macos

I faced this issue previously on macOS and some docker container, but it wasn't critical for me.

Looks like it's time to investigating it. @abunashir could you please send verbose log from `gem install` or `bundle install`  there must be some statement about why it's going to be compiled from scratch

**Comment by abunashir** [comment]
I manually fixed it by installing the `automake` for now, but I can send you the logs if I see the same issue again.

**Comment by CAMOBAP** [comment]
@abunashir if it will be ok for you, could you please temporary remove `autotools` and `expressir`, `rice` gems, and try to install them again to generate verbose logs?

**Comment by ronaldtse** [comment]
I'm sure this is addressed but for the record, the gem in question is `expressir` not `expressive` 😉 

Aren't the linux binary gems already available? Why would installation require compilation?

<img width="291" alt="Screenshot 2021-03-16 at 3 46 51 PM" src="https://user-images.githubusercontent.com/11865/111273485-d6035800-866e-11eb-84d9-71f5cf94463c.png">

**Comment by abunashir** [comment]
This is little bit wired, I just created another ubuntu VM with the same image I normally use, and looks like if I run `gem install metanorma-cli` then it seems to be working without any issue.

But if I run the `bin/setup` script on the Metanorma-CLI project then it's fails [with this output](https://gist.github.com/abunashir/dfa6a2c60d74ba557580d089e44de2c5). The image is using this [bootstrap.sh](https://github.com/abunashir/dotfiles/tree/master/workstation) script with ruby version 2.6.3. Let me know if you need a VM to reproduce it, then I can spin up one for you.

**Comment by CAMOBAP** [comment]
@abunashir thanks a lot for steps , this is more than enough to start

**Comment by ronaldtse** [comment]
I saw this message in the output:

```
Fetching rice 3.0.0
Installing rice 3.0.0 with native extensions
Building native extensions. This could take a while...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

This is because of the `rice` gem due to `expressir`?

**Comment by CAMOBAP** [comment]
@ronaldtse `expressir` depends on `rice` gem. But we remove this dependency for gem with prebuilt exetnsion:
 - https://rubygems.org/gems/expressir/versions/0.2.21-x86_64-linux - have no `rice` dependency
 - https://rubygems.org/gems/expressir/versions/0.2.21 - have `rice` dependency

**Comment by ronaldtse** [comment]
Seems that this is done, thanks!
