### ISSUE TITLE
Ruby 3.0 support

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#235]
- https://github.com/metanorma/metanorma-cli/pull/233#issuecomment-802135325 - details

**Comment by abunashir** [comment]
@CAMOBAP: same with this one, I guess you already did the work right? can we close this one too?

**Comment by CAMOBAP** [comment]
@abunashir right 3.0 passed on CI now

**Comment by ronaldtse** [comment]
Thanks guys!

**Comment by ronaldtse** [comment]
@CAMOBAP in this case can we add Ruby 3.0 for all the relevant gems? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse I think we already did this, should we make it as 'required' ? (because right now it is 'experimental ~ allow to fail)

**Comment by ronaldtse** [comment]
@CAMOBAP Let's change experimental to required for the gems that pass, and we make a list of those that don't pass 3.0, and upgrade those independently. Thanks!
