### ISSUE TITLE
Windows 7 installation issues

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-cli#237]
I'm trying to install Metanorma v.1.4.7 on Windows 7 (SP1 64-bit with all latest updates).

1. The command `choco install metanorma -y` tries to install Python 3 3.9.4 and ended with error, because version 3.9.4 can't be installed in Win7, only Win 8 and above. When I installed Python 3 3.8.9 (latest compatible version with Win7) via `choco install python --version=3.8.9`, then metanorma installed successfully. It's possible to specify an exact version of Python into installation package to allow Win7 user run metanorma software?
2. It seams metanorma 1.4.7 doesn't contain Ruby. I've tried run `bundle install` in some repositories and this command can't be found.
3. After manually installation Ruby by `choco install ruby --version=2.6.0.1` I've tried to run `bundle update` in the repository https://github.com/metanorma/annotated-express/, and got the error for byebug package:
```
D:\Metanorma\Stepmod\annotated-express\data\documents\resources\fundamentals_of_product_description_and_support>b
undle install
Fetching https://github.com/metanorma/metanorma-iso
Fetching gem metadata from https://rubygems.org/..............
Resolving dependencies...................
Using rake 13.0.3
Using public_suffix 4.0.6
Using addressable 2.7.0
Using cabin 0.9.0
Using arr-pm 0.0.10
Using asciidoctor 2.0.12
Using asciimath 2.0.2
Using htmlentities 4.3.4
Using mini_portile2 2.4.0
Using nokogiri 1.10.10 (x64-mingw32)
Using rsec 1.0.0
Fetching asciimath2unitsml 0.2.5
Installing asciimath2unitsml 0.2.5
Using latex-decode 0.3.2
Using bibtex-ruby 6.0.0
Using blankslate 3.1.3
Using bundler 2.2.15
Fetching byebug 11.1.3
Installing byebug 11.1.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/byebug-11.1.3/ext/byebug
C:/tools/ruby26/bin/ruby.exe -I C:/tools/ruby26/lib/ruby/2.6.0 -r
./siteconf20210406-4056-au4yzo.rb extconf.rb
creating Makefile

current directory:
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/byebug-11.1.3/ext/byebug
make "DESTDIR=" clean
current directory:
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/byebug-11.1.3/ext/byebug
make "DESTDIR="
make failedNo such file or directory - make "DESTDIR="

Gem files will remain installed in
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/byebug-11.1.3 for inspection.
Results logged to
C:/tools/ruby26/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/byebug-11.1.3/gem_make.out

An error occurred while installing byebug (11.1.3), and Bundler cannot continue.
Make sure that `gem install byebug -v '11.1.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  byebug
```

**Comment by CAMOBAP** [comment]
@Intelligent2013 

1.  Looks like a `chocolatey` related issue because `metanorma` depends on `python 3.x`: 
    - https://community.chocolatey.org/packages/metanorma#dependencies
    - https://github.com/metanorma/chocolatey-metanorma/blob/master/metanorma.nuspec#L28
2. That's true because we build a native executable with https://github.com/metanorma/ruby-packer/
3. To be able to build native extensions you need `msys2` installed, please check https://community.chocolatey.org/packages/ruby#notes

**Comment by Intelligent2013** [comment]
>1.  Looks like a `chocolatey` related issue because `metanorma` depends on `python 3.x`:  

It seems ok, because 3.9.4 >= 3.0.1. My question was about can we set upper limit i.e.  3.0.1. <= version <= 3.8.9 ?

> P.S. Could you please post the exact output of choco install python will it try to install 3.9.4 by default? (this information will need to post an issue to chocolatey)

Looks like a `chocolatey` tries to install latest version (at this moment) of Python independent of os compatibility.

```
choco install python
Chocolatey v0.10.15
Installing the following packages:
python
By installing you accept licenses for the packages.
Progress: Downloading python 3.9.4... 100%

python3 v3.9.4 [Approved]
python3 package files install completed. Performing other installation steps.
The package python3 wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): Y

Installing 64-bit python3...
ERROR: Running ["C:\ProgramData\chocolatey\lib\python3\tools\python-3.9.4-amd64.exe" /quiet InstallAllUsers=1 PrependPat
h=1 TargetDir="C:\Python39" ] was not successful. Exit code was '1'. See log for possible error messages.
The install of python3 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.

python v3.9.4 [Approved]
python package files install completed. Performing other installation steps.
 The install of python was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - python3 (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare

C:\Windows\system32>
```
![image](https://user-images.githubusercontent.com/5559926/113743879-d42c3200-970c-11eb-8200-47fca409586a.png)

**Comment by CAMOBAP** [comment]
> It seems ok, because 3.9.4 >= 3.0.1. My question was about can we set upper limit i.e. 3.0.1. <= version <= 3.8.9 ?

@Intelligent2013 I have checked output and there are no Windows 7 specific issues in the output, so to me, it looks like an issue with the Python installer file, could you please attach `chocolatey.log` also.

IMHO we should be as less restrictive as possible and don't restrict all user just because of the issue on specific windows version

**Comment by Intelligent2013** [comment]
@CAMOBAP  Yes, there is Python installer issue. Python 3.9.4 requires Win 8 or later.
Chocolatey log here: [chocolatey.log](https://github.com/metanorma/metanorma-cli/files/6266335/chocolatey.log)

I've download version 3.9.4 manually from https://www.python.org/ftp/python/3.9.4/python-3.9.4-amd64.exe and run it.
Here is log: [Python 3.9.4 (64-bit)_20210406195324.txt](https://github.com/metanorma/metanorma-cli/files/6266357/Python.3.9.4.64-bit._20210406195324.txt)
```
[14A8:14CC][2021-04-06T19:53:24]e000: Detected Windows 7
[14A8:14CC][2021-04-06T19:53:24]e000: Windows 8.1 or later is required to continue installatiohttps://github.com/aboutn
```

**Comment by CAMOBAP** [comment]
@Intelligent2013 good finding! thanks for the information, I will report a ticket to chocolatey

**Comment by CAMOBAP** [comment]
Oh, [this isn't but this is a feature (](https://docs.chocolatey.org/en-us/create/create-packages#install-only-on-some-versions-of-windows)

> If the package failed and it was a dependency of a higher level package that installed software, it would cause issues attempting to install that software on different versions of Windows. Since about 5% of the packages apply to this exception, stick with the above thoughts for packages.
📝 NOTE We will ultimately enhance the nuspec and take care of this for you automatically. Until we get there, follow the above avenue.

@Intelligent2013 looks like all questions/issues sorted out, feel free to close it or please mention if I missed something

**Comment by Intelligent2013** [comment]
> 3. To be able to build native extensions you need `msys2` installed, please check https://community.chocolatey.org/packages/ruby#notes

I've installed `msys2`, but the error still exist.  I have to play around with it. What is Ruby version should I install - 2.5, 2.6, 2.7, 3.0....?
Is there any step by step guide how to install all needed software?

**Comment by Intelligent2013** [comment]
> Oh, [this isn't but this is a feature (](https://docs.chocolatey.org/en-us/create/create-packages#install-only-on-some-versions-of-windows)

Ok, let's skip this issue. In any case I've found a solution how to bypass it.

**Comment by ronaldtse** [comment]
@Intelligent2013 @CAMOBAP can we write down our findings and make a blog post or support post? This will help many users and prevent them from forwarding these issues back to us.

**Comment by CAMOBAP** [comment]
@ronaldtse @Intelligent2013 we had such post before packed-mn, I will find it

The issue which @Intelligent2013   faced with is ruby related (not metanorma related)

**Comment by Intelligent2013** [comment]
I've installed `Ruby+Devkit 2.7.2-1 (x64)` (https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.7.2-1/rubyinstaller-devkit-2.7.2-1-x64.exe) and issue has gone.
Closing.

**Comment by CAMOBAP** [comment]
BTW Pervioulsy when we had gem based chocolatey page, this page was actual https://www.metanorma.org/blog/2018-12-25/metanorma-on-windows-via-chocolatey/
