### ISSUE TITLE
Site generation functionality masks underlying failures

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#238]
We have encountered this multiple times but this time in the context of site generation. 

Metanorma site generation kicks off the compilation of multiple documents and their multiple outputs. 

If a single output fails, the compilation of the document is considered to have failed immediately and should abort. 

If a single document fails, the compilation of the collection is considered to have failed immediately and should abort. 

If the user wishes to continue the compilation even when an output or a document failed, then a command option should be given for “continue on error”. 

@abunashir do you have time for this? Thanks!

**Comment by abunashir** [comment]
Yes, I will have a look into this

**Comment by abunashir** [comment]
Hey @ronaldtse: I'm trying to understand this: what is the current behaviour? does it continues even if there is some compilation error at the moment and we don't want it? or the other way around?

Can you share some example so I could reproduce this issue?

**Comment by ronaldtse** [comment]
I’m not sure if this problem has been fixed (ping @camobap). 

I believe right now site generation skips the failed document without aborting or returning any error. The correct behavior is to abort on error.

**Comment by CAMOBAP** [comment]
@ronaldtse @abunashir mostly it doesn't relate to the site-gen byitself. but related to this part of the code https://github.com/metanorma/metanorma/blob/master/lib/metanorma/compile.rb#L221-L232 previously it just suppressed all errors (just print and don't re-raise them)

Here is a new PR related to this https://github.com/metanorma/metanorma/pull/186

In this new PR I propose to fail for any exception which contains "Fatal:"

Please let me know how do you think

**Comment by abunashir** [comment]
@CAMOBAP: should these be closed now?

//cc: @ronaldtse

**Comment by CAMOBAP** [comment]
@abunashir I think so

**Comment by ronaldtse** [comment]
Thanks guys!
