### ISSUE TITLE
Workflow for CLI release

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cli#245]
@CAMOBAP has raised the prospect of doing hotfix releases of metanorma-cli, to address hotfixes in packed-mn

I am concerned that this is going to break our current arrangement with external docker instances, such as with NIST. @CAMOBAP reports he was unfamiliar with those instances. Alex is also considering triggering an mn-docker run on GitHub Actions given just a tag update on metanorma-cli, without a gem publication. 

I am seeking confirmation that the following workflow I have been following is still valid. If a different workflow is needed, I need it to be documented.

* For *any* prospective release of metanorma-cli, I run rspec locally, and then publish the gem as a prerelease version
* The prerelease version triggers mn-docker to run, and mn-docker presumably needs the updated prerelease gem in rubygems, and not just on github
* If mn-docker succeeds in Github Actions, I release metanorma-cli as a new version. (I will be using X.Y.Z versions henceforth, in order not to collide with hotfix releases Alex may do.)
  * Given the  horrid interdependencies of the Metanorma stack by the way, I think hotfixes on  metanorma-cli, at the peak of that stack, are a bad idea.
* A proper release of metanorma-cli triggers docker runs in external agencies such as NIST, and therefore all releases of metanorma-cli need to be pretested in this fashion.

**Comment by ronaldtse** [comment]
I think we need to draw out the dependency graph and discuss those relationships.

packed-mn and the docker images are at the most downstream. These are the platform-dependent deliverables. 

metanorma-cli is at the end of the development chain. This is the platform-independent deliverable. 

The principle here on versioning is that once the upstream version is released, downstream deliverables get built and released. 

Therefore metanorma-cli versions should be independent from the versions of the downstream deliverables, and metanorma-cli versions should not be used as a versioning mechanism for packed-mn and docker.

**Comment by CAMOBAP** [comment]
@opoudjis @ronaldtse thanks for this discussion

> Therefore metanorma-cli versions should be independent from the versions of the downstream deliverables, and metanorma-cli versions should not be used as a versioning mechanism for packed-mn and docker.

We are gaining some benefits from this:
 - During troubleshooting: chance that end user will report wrong version are minimal
 - Release automation: goes straight forward

Generally I see your point (about version independency between CLI gem and downstream deliverables).
I'm ok to discuss other approaches for versioning

**Comment by CAMOBAP** [comment]
As far as I see we are following this approach, and it works better then previous one (because we have one more stage to fix possible issues before snap/brew/choco/docker delivery)
