### ISSUE TITLE
Site generation not respecting document type in index badge

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#250]
Somehow the index document entry badge is not respecting the document type. I think this is falling back to "standard" as a default because the document type isn't propagated to the index page.

![image](https://user-images.githubusercontent.com/11865/127845350-8e06658a-4b0d-4f62-83c4-a17c642db8f7.png)

Notice that the document type is `engineering-report`, but it's showing up as "standard" on the index.

```adoc
= Title
:doctype: engineering-report
:status: published
:committee: technical
:docnumber: xx-yyy
:received-date: 2021-07-19
...
```

Originally from: https://gitlab.ogc.org/ogc/T17-D022-Model-Driven-Standards-ER/-/issues/6

**Comment by ronaldtse** [comment]
@abunashir would you have time to deal with this one? Thanks!

**Comment by abunashir** [comment]
Sure, I will have look into it soon :)

**Comment by abunashir** [comment]
Hey @ronaldtse: I was looking into this, but all we are doing here is to delegate the html generation to relaton cli, and I guess [bibliographic_item.rb](https://github.com/relaton/relaton-bib/blob/master/lib/relaton_bib/bibliographic_item.rb#L36) doing some type verification here, could this be related?

@andrew2net: Do you have any context, why it might fallback to standard here by any chance?

**Comment by andrew2net** [comment]
@abunashir  there are `type` and `doctype` attributes. The `type` attribute is always "standard". The `doctype` attribute should come from a source.

**Comment by ronaldtse** [comment]
I've sent @abunashir the source for debugging.

**Comment by abunashir** [comment]
> @abunashir there are `type` and `doctype` attributes. The `type` attribute is always "standard". The `doctype` attribute should come from a source.

@andrew2net: I guess I might be missing something here, is this [the template ](https://github.com/relaton/relaton-cli/blob/master/templates/_document.liquid#L20) that's rendering standing label there, how exactly are we setting the `document.type` attribute?

**Comment by andrew2net** [comment]
@abunashir it should be the `document.doctype` attribute. The `document.type` is always "standard".
For OGC allowed doctypes listed in this [grammar](https://github.com/metanorma/metanorma-model-iso/blob/a8ce635e92486e6fbc6af92d24a78a130c00aebc/grammars/ogc.rnc#L9)
For other flavor relaton-* gems see appropriated grammar [here](https://github.com/metanorma/metanorma-model-iso/tree/master/grammars).

**Comment by abunashir** [comment]
@ronaldtse: I've updated the relaton-cli, to display the correct `doctype`, once that is merged and released then this issue should be fixed. But fair warning, this will change every other collection that is using this default template, so please let me know if there is anything there.

//cc: @andrew2net, @ronaldtse

**Comment by ronaldtse** [comment]
Confirm fixed in https://github.com/relaton/relaton-cli/pull/99. Thanks @abunashir !

<img width="870" alt="Screenshot 2021-08-16 at 5 15 15 PM" src="https://user-images.githubusercontent.com/11865/129540390-51d759a8-98c3-41a8-ab7a-416dc3f796a8.png">
