### ISSUE TITLE
Reconsider PlantUML inclusion in default Metanorma package

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#254]
Some OGC users utilize PlantUML for diagramming needs.

> Using the metanorma build in Gitlab [...], we don't seem to be able to generate image from PlantUML.
> The build will fail on the HTML generation, but generate the PDF (without the PlantUML being converted).

https://gitlab.ogc.org/ogc/T17-D022-Model-Driven-Standards-ER/-/issues/8

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by opoudjis** [comment]
It is not, @ronaldtse: you are misdiagnosing the issue. This is an isodoc HTML issue.

**Comment by ronaldtse** [comment]
So it's the fallback not working?
1. PlantUML code goes into the XML as proper source code
2. Isodoc is not rendering it as source but PDF is?

**Comment by ronaldtse** [comment]
Here's the PlantUML source:

```adoc
@startuml
package "FOO (NNN)" {
  JMS - [FOO Some Service (FSS)]
  database "Some subscription" {
    [Roads]
  }

  database "Other" {
    [Bike parks]
  }
}

package "Q11 BikeAPIs" {
  [Information Fetch]
  [LLL]
  [DB system]
  HTTPS - [proxy]
}

[Information Fetch] --> JJJ : XXX
[Information Fetch] --> [DB system] : SQL
[Information Fetch] --> [Roads] : Shape

[LLL] --> [Roads] : Shape
[LLL] --> [Bike parks] : AIXM
[LLL] --> [DB system] : SQL

[proxy] <--> [DB system] : SQL
```

I'm not sure whether there was an `@enduml`.

**Comment by CAMOBAP** [comment]
- for Linux snap has embedded plantuml https://github.com/metanorma/metanorma-snap/blob/master/snap/snapcraft.yaml#L43-L50
 - https://github.com/metanorma/homebrew-metanorma/commit/67bb8a222e3acc16110a04d6814205542f42a5ef
 - https://github.com/metanorma/chocolatey-metanorma/commit/650bd511bafa4fabfb1ec599ebd93e8493ab0298

DOne
