### ISSUE TITLE
Support template repositories using `main` and also `master` branches (for backwards compatibility)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#264]
Following the recent change in the default git branch name to `main`, the CLI needs to support `main` and also `master` branches for template repositories.

* [ ] https://github.com/metanorma/mn-templates-iso/issues/35
* [ ] https://github.com/metanorma/mn-templates-nist/issues/16
* [ ] https://github.com/metanorma/mn-templates-iec/issues/24
* [ ] https://github.com/metanorma/mn-templates-cc/issues/30
* [ ] https://github.com/metanorma/mn-templates-itu/issues/33
* [ ] https://github.com/metanorma/mn-templates-ietf/issues/23
* [ ] https://github.com/metanorma/mn-templates-m3aawg/issues/6
* [ ] https://github.com/metanorma/mn-templates-un/issues/5
* [ ] https://github.com/metanorma/mn-templates-ogc/issues/48

**Comment by CAMOBAP** [comment]
@ronaldtse just checked `ruby-git` it will correctly handle `main` and `master` default branches

As far as I see no extra actions required
