### ISSUE TITLE
metanorma new: generate correct metanorma.yml config

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#268]
Related issues/PRs:
 - https://github.com/metanorma/mn-templates-ogc/pull/46
 - https://github.com/metanorma/mn-templates-ogc/issues/43
 - https://github.com/metanorma/metanorma/issues/229
 - https://github.com/metanorma/metanorma/issues/228

it will be nice to have `metanorma.yml` correctly generated after `metanorma new` command, for now we have a workaround like https://github.com/metanorma/mn-templates-ogc/pull/46/files#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94R63-R69

But the probably right place for this is `metanorma new` command

cc @ronaldtse

**Comment by ronaldtse** [comment]
Metanorma new is only copying the template repo contents, if metanorma.yml is placed under “common”, it will be copied in.

**Comment by CAMOBAP** [comment]
@ronaldtse as far as I remember unfortunatelly not all our templated have `document.adoc` as a root file. should we do either:
1. keep templates consistent and use `document.adoc` as name of the rood document
2. or leave `metanorma.yml` generation up to `metanorma new`

If you ask me I'm prefer first option, but as I said I'm not sure that it will works for all templates

**Comment by ronaldtse** [comment]
Definitely first option, much easier to deal with.

**Comment by CAMOBAP** [comment]
@ronaldtse I think makes sense to generate metanorma.yml if it's missing, what do you think?

**Comment by ronaldtse** [comment]
Yes @CAMOBAP , can we just add "metanorma.yml" to the template "common/" directory, and always use document.adoc as the name?

**Comment by CAMOBAP** [comment]
@ronaldtse I observed that metanorma.yml from `metanroma-cli/templates/base/metanorma.yml` overwrites `common/metanorma.yml`, which probably incorrect, could you please confirm?

**Comment by ronaldtse** [comment]
As long as we have one copy, it is fine. I want to keep all the common files under the same location. Thanks.

**Comment by CAMOBAP** [comment]
to be on the same page we have two kind of "common" directories:
 - https://github.com/metanorma/metanorma-cli/tree/main/templates/base
 - https://github.com/metanorma/mn-templates-*/tree/master/common

In my understanding it's critically important that `mn-templates-*/common` must overwrite `metanorma-cli/templates/base`

For example:
 - latest released `metanorma-cli` contains `metanorma-cli/templates/base/metanorma.yml`:
    ```
    ---
    metanorma:
      deploy:
        email: "ci@metanorma.org"
    ```

 - `mn-templates-cc/common/metanorma.yml` contains:
    ```
    metanorma:
      source:
        files:
          - document.adoc
    ```

`metanorma new ...` will keep first `metanorma.yml` which is wrong

My proposal:
 - keep master copy in `metanorma-cli/templates/base/metanorma.yml`:
 - fix logic in `metanorma new` to keep priority of  `common` higher than `metanorma-cli/templates/base/`

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP we don't need this, it was only there for the old version that used an email for SSH deploy.

```yaml
---
metanorma:
  deploy:
    email: "ci@metanorma.org"
```
