### ISSUE TITLE
Processors related debugging information

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-cli#27]
Hey Guys, whenever we use any command from metanorma / relaton cli, then it always kept outputting the processor information in the terminal, is this necessary or is there any specific reason we are doing that?

Eg:

<img width="761" alt="screenshot 2019-03-03 16 50 58" src="https://user-images.githubusercontent.com/1220911/53697758-f425f480-3dd4-11e9-8eff-82d27bfe3176.png">

//cc @ronaldtse, @opoudjis

**Comment by ronaldtse** [comment]
@abunashir good question. This started as a debug message shown on gem loading, but it is not necessary. The only thing we want to support is the indication that a custom gem has loaded.

For example, if we implement a new or custom gem that is not in `metanorma-cli` yet, if we use the type argument `-t xxx`, then `metanorma-cli` will attempt to load the `metanorma-xxx` gem. We may want that message.

Better yet, maybe we should have a "debug" or "verbose" mode (like `ssh -vv` `ssh -vvv`) to show debug messages?

**Comment by abunashir** [comment]
Hi @opoudjis, did you have a chance to look into this one yet, if not please let me know, I might be able to help :)

**Comment by opoudjis** [comment]
Given everything that I have been deluged with, no, I have not, and since I've demoted it to mid priority, I am unlikely to get to it for a couple of months. 

I clearly am overcommitted, and I am very reluctant to continue working on metanorma-cli, since you've refactored it so much anyway. You ok to take this task over?

**Comment by abunashir** [comment]
Sure, I will put this one in my list then :) Thanks @opoudjis!
