### ISSUE TITLE
Add mn-sample-* test jobs for a GHA matrix build

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#273]
We want to test mn-sample-* compilation with a locked version of metanorma-cli. This is similar to https://github.com/metanorma/metanorma-docker/pull/145.

**Comment by CAMOBAP** [comment]
Implement the same approach for metanorma-* flavor gems to resolve https://github.com/metanorma/metanorma/issues/275

**Comment by CAMOBAP** [comment]
Done
