### ISSUE TITLE
Use semantic versioning (semver) v2 for (pre-)releases of all gems

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#276]
The latest Docker build actions (https://github.com/metanorma/metanorma-docker/pull/151) require version numbers that match the semver scheme. 

* https://semver.org

The only change that we need to adopt is the "prerelease version": https://semver.org/#spec-item-9

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.

Right now, metanorma-cli uses `x.y.zpre` as the prerelease version, which breaks the Docker builds. We need to adopt something like `x.y.z-pre` or `x.y.z-alpha` or `x.y.z-alpha.1` as the version tag.

**Comment by opoudjis** [comment]
Done.
