### ISSUE TITLE
Gem loading error message not informative

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#278]
I just encountered this issue when using the Git version of metanorma-ieee. This error is not informative to the user, and does not give enough hints for debugging.

We should show the underlying error and also give the user information on where to report this error.

```
[metanorma] Error: loading gem `metanorma-ieee` failed. Exiting.
```

**Comment by CAMOBAP** [comment]
@ronaldtse should we report those errors to processor repos too or it's ok to report it to `metanorma-cli` repo? Maybe you can suggest a message template?

**Comment by ronaldtse** [comment]
How about something like this?

```
Error: {error message}
An exception with Metanorma has occurred.

If this problem persists, please report this issue at this link and we shall respond
as soon as we can:

* https://github.com/metanorma/metanorma/issues/new

You may either describe your issue, or opt to attach the generated error report
at `{date-time}-error.log`, which contains additional system information
potentially useful for fixing the issue.

Your valuable feedback is very much appreciated!

- The Metanorma team
```

**Comment by CAMOBAP** [comment]
Ready for review

**Comment by ronaldtse** [comment]
Requested some updates in metanorma/metanorma#254. Thanks!

**Comment by opoudjis** [comment]
Closing ticket, since the remaining issue of sanitising user information is a new ticket, https://github.com/metanorma/metanorma-cli/issues/287
