### ISSUE TITLE
Extract images and requirements

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cli#28]
Currently there is functionality to extract sourcecode fragments. Extend this to images and requirements, and label it generically as extract.

**Comment by opoudjis** [comment]
Command will accordingly change from metanorma -S to metanorma -e

**Comment by ronaldtse** [comment]
Potential improvements:
* types of inserts to extract (requirements, images, source code...)

**Comment by opoudjis** [comment]
Reluctant to overcomplicate this.

**Comment by ronaldtse** [comment]
People who want requirements/sourcecode may not want images.

**Comment by opoudjis** [comment]
And they can ignore the images folder. But fine, we can do this like the -x option, where you name what you want.

**Comment by ronaldtse** [comment]
Yay! Thanks!

**Comment by ronaldtse** [comment]
And by `-x` we're choosing amongst the tag names: `requirement`, `image`, `sourcecode`? It sounds like we need to consolidate these in the StandardDoc model.

**Comment by opoudjis** [comment]
Not to me.

I have added filenames to requirements, images, and sourcecode in the standarddoc model; I don't see what else needs to be done. Those tag names certainly don't belong to the standarddoc model in a meaningful way.

**Comment by ronaldtse** [comment]
i.e. requirement, image, sourcecode can all take filenames.

**Comment by opoudjis** [comment]
Right. I've done that already in the model.
