### ISSUE TITLE
`metanorma site generate` with a collection source file generates output in the wrong location

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#284]
This is a bug in the functionality implemented in https://github.com/metanorma/metanorma-cli/issues/205.

This refers to a bug in the functionality implemented in https://github.com/metanorma/metanorma-cli/issues/205

Notice that `collection.yaml` has this line:
https://github.com/metanorma/bipm-si-brochure/blob/a588390f6d323ae9df8ad119027d440543bf5cd8/collection.yml#L30

But the `site generate` command output location should override the specified output folder, because the whole point of `site generate` is to keep the generated output under `/site/` for deployment to a website.

This case is similar to when we run the normal `metanorma` command:
```sh
$ metanorma compile path/document.adoc
# => generates under path/document.xml
$ metanorma site generate config.yml # which points to path/document.adoc
# => generates under site/path/document.xml
```

Please refer to https://github.com/metanorma/bipm-si-brochure/pull/186 on how to reproduce this problem.

**Comment by abunashir** [comment]
Hi @ronaldtse, this should be fixed in the attached PR :)
