### ISSUE TITLE
(URGENT) Metanorma private gems not tested in the release of metanorma-cli

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#289]
@opoudjis will provide details.

**Comment by ronaldtse** [comment]
We must ensure all private gems pass tests before the metanorma-cli gem can be released.

**Comment by CAMOBAP** [comment]
> We must ensure all private gems pass tests before the metanorma-cli gem can be released.

What kind of tests do we mean? Just compilation of mn-samples-{nist|bsi} or anything else?

**Comment by CAMOBAP** [comment]
For now we have "post-release" testing in `metanorma-docker[-private]`

Also, we have `gems-test` workflow https://github.com/metanorma/mn-samples-iso/blob/main/.github/workflows/test.yml
Which looks broken right now. For `gems-test` workflow the idea was to trigger it each time after changes in corresponding  `metanorma-*` gem

I will check why this is happening. @ronaldtse @opoudjis let me know if anything else should be done in the scope of this task

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis any ideas/suggestions are welcome

**Comment by opoudjis** [comment]
> > We must ensure all private gems pass tests before the metanorma-cli gem can be released.
> 
> What kind of tests do we mean? Just compilation of mn-samples-{nist|bsi} or anything else?

That is all I had in mind.

**Comment by CAMOBAP** [comment]
@ronaldtse feel free to reopen if you have any ideas
