### ISSUE TITLE
Add filenames for assets to be extracted to

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cli#29]
And respect those filenames in extraction. The extraction has scope over images, sourcecode, and requirements. There need to be sensible defaults if no filename has been provided (which is currently the case: consecutive numerals). But images will always have filenames.

**Comment by ronaldtse** [comment]
This is excellent! For images, we can always use `figure-X` as default?

**Comment by opoudjis** [comment]
Images won't always have file names: they won't if they are data URIs.

**Comment by ronaldtse** [comment]
Images only specified as data URIs should still be extracted according to some default filename pattern, e.g. "figure-X.png"

See: https://stackoverflow.com/questions/15995015/open-and-save-base64-encoded-image-data-uri-in-ruby

**Comment by opoudjis** [comment]
The extraction command shall change from `metanorma -S` (specific to sourcecode) to `metanorma -e` (extracting all of images, sourcecode, and requirements, into separate directories).

**Comment by opoudjis** [comment]
Implemented for sourcecode: either unsuffixes consecutive numbers in sourcecode/ subdirectory, or nominated filename.

**Comment by opoudjis** [comment]
Implemented for sourcecode, images, and requirements, with defaults: figure%04d.(suffix), sourcecode%04d.txt, and (requirement|permission|recommendation)%04d.xml.

**Comment by ronaldtse** [comment]
Can we have a "dash" in `{type}-%04d.{suffix}`? Thanks!

**Comment by opoudjis** [comment]
Done, and renamed figure- to image- for consistency.
