### ISSUE TITLE
Windows: `site generate` command leading to tempfile.rb failure on Ruby 3.1

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#290]
This is received from a Metanorma user on Windows, using Ruby 3.1 with Bundler (i.e. not packed-mn). The site has been generated properly, but apparently the temp files could not be removed afterwards.

```
> bundle exec metanorma site generate
...
Site has been generated at (proper location)
C:/programs/ruby31/bin/metanorma: warning: Exception in finalizer #<Tempfile::Remover: 0x000002a9cefc6820 @pid=XXXXX. @tmpfile=#(File:C:/Users/XXXXX/AppData/Local/Temp/isodoc20221103-XXXXX-RANDOM (closed))>
C:/programs/ruby31/lib/ruby/3.1.0/tempfile.rb:265:in 'unlink':
Permission denied @ apply2files - C:/Users/XXXXX/AppData/Local/Temp/isodoc20221103-XXXXX-RANDOM (Errno::EACCES)
    from C:/programs/ruby31/lib/ruby/3.1.0/tempfile.rb:265:in 'call'
...
```

A related issue has been reported at Ruby Lang:
* https://bugs.ruby-lang.org/issues/18784#note-8
* and FileUtils https://github.com/ruby/fileutils/pull/99/files

This is the issue we're seeing:
* https://github.com/rubocop/rubocop/pull/10955
* https://github.com/rubocop/rubocop/pull/10965

I suspect that the problem is that the tmpfile is not marked as "closed" and therefore cannot be removed. This seems to be a Windows behavior from reading the cited tickets above.

Perhaps the key is we need to "remove references to File objects before unlinking" in Windows.

**Comment by CAMOBAP** [comment]
Already fixed by @alexeymorozov in [metanorma](https://github.com/metanorma/metanorma/pull/307/files)
