### ISSUE TITLE
Next iteration of improving release process

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#302]
### Intro

In the scope of https://github.com/metanorma/metanorma-cli/issues/273 I "moved" samples testing on `metanorma-cli` side

Previously `metanorma-cli` just "triggered" CI on templates/samples with `repository_dispatch` and it was really hard to track

### Proposal

1. I think we can move out of `pre`-releases because we test samples/templates more regularly and it's easy to track. This will simplify releases for @opoudjis, he will only be responsible for release gems `metanorma-cli` `metanorma-*`
2. @CAMOBAP is responsible to release/maintain `docker/packed-mn/snap/choco/brew` packages/deliverables
3. @CAMOBAP add samples/templates testing on `metanorma-*` side. Example https://github.com/metanorma/metanorma-iso/pull/950

@ronaldtse @opoudjis please share your feedback on the proposals above

**Comment by opoudjis** [comment]
Important note to make on current state of affairs.

https://github.com/metanorma/metanorma-cli/actions/runs/4403928757 is taking five (5) hours to run.

AND THIS IS RUNNING ON ONLY A QUARTER OF ALL DOCUMENTS IN SAMPLES REPOS.

The previous arrangement with docker involved maybe 3 hrs delay. 

**I will not under any circumstances wait around for five hours for the results of a test run.**

In fact, if I am made to wait anything more than an hour, I will, as I have been explicit, quite simply ignore the test run and release anyway. 

If I can ignore pre-release, I will; I'm fine to come back and do a remedial release some time later, although I'm not at all inclined to do a rerun from scratch, and will end up testing it before next release.

I actually don't have any comments on the proposal. In theory, sure, if we can have indicative testing during release that alerts us to problems, to prevent problems, we should. 

But I need a workable test regimen for releases. 5 hours, on a set of documents 1/4 the size of what it was before, is not workable.

**Comment by opoudjis** [comment]
@CAMOBAP Can this issue be closed?

**Comment by CAMOBAP** [comment]
I think yes
