### ISSUE TITLE
Remove metanorma-m3aawg warning

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#304]
The latest version of Metanorma CLI produces the following warning:
```
[metanorma] Error: flavor gem metanorma-m3aawg not present
```

We have dropped default support for m3aawg and should no longer show this warning.

**Comment by CAMOBAP** [comment]
m3aawg removed from https://github.com/metanorma/metanorma-cli/blob/main/.github/workflows/samples-smoke-matrix.json (now all our deliverables reuse it for tests)
