### ISSUE TITLE
(URGENT) Version bump for release due to relaton-render crash with all RFC bibliographic entries

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#311]
https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/actions/runs/5880384918/job/15946558490

```
/usr/local/bundle/gems/relaton-render-0.5.12/lib/relaton/render/fields/fields.rb:112:in `role_inflect'
/usr/local/bundle/gems/relaton-render-0.5.12/lib/relaton/render/fields/fields.rb:36:in `role_fields_format'
/usr/local/bundle/gems/relaton-render-0.5.12/lib/relaton/render/fields/fields.rb:12:in `compound_fields_format'
/usr/local/bundle/gems/relaton-render-0.5.12/lib/relaton/render/general/render.rb:170:in `block in citations1'
/usr/local/bundle/gems/relaton-render-0.5.12/lib/relaton/render/general/render.rb:168:in `each'
/usr/local/bundle/gems/relaton-render-0.5.12/lib/relaton/render/general/render.rb:168:in `each_with_object'
/usr/local/bundle/gems/relaton-render-0.5.12/lib/relaton/render/general/render.rb:168:in `with_index'
```

This issue is fixed here
* https://github.com/relaton/relaton-render/issues/46

But the docker container and packed-mn has not been re-released.

This is an URGENT release.

**Comment by ronaldtse** [comment]
IEEE (@reeseplews) is waiting for this

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP @opoudjis !

**Comment by ReesePlews** [comment]
@CAMOBAP i have just checked the [generate](https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/actions/runs/5897725779) on the project but it still is not working? did i check too soon?

**Comment by ronaldtse** [comment]
@CAMOBAP I think the metanorma-snap package publication failed? But did the others succeed?

**Comment by CAMOBAP** [comment]
Quick update:

### Docker (released)

- `metanorma/metanorma:1.8.2-pre` released and available to use

### Chocolatey (blocked)

- `git` package installation issue. Will be investigated separately https://github.com/metanorma/chocolatey-metanorma/issues/76

### Snap package (released)

It looks like the officially recommended command to install the `candidate` package is wrong

This is how you can install `candidate` snap:

```sh
sudo snap refresh metanorma --channel=latest/candidate
sudo snap list metanorma --all
```

### Homebrew (released)

Released 1.8.2_pre, can be installed with `brew install metanorma/metanorma/metanorma`

---

This was `-pre` release, and once https://github.com/metanorma/chocolatey-metanorma/issues/76 is resolved I propose to do "stable" `1.8.2` release. @ronaldtse  make sense?

cc @ReesePlews

**Comment by ReesePlews** [comment]
hi @CAMOBAP and @ronaldtse 

sorry to bother you both about this but there still seems to be an issue, perhaps not here, but in related to something (perhaps  https://github.com/metanorma/chocolatey-metanorma/issues/76 ) that is causing problems in the IEEE version i am using in a project.   i checked the "generate" on the IEEE project a couple of hours ago but it was still not working correctly.  is that related to issue 76?

will this be installed automatically on the project site, or is there something we need to do? please let me know if there is.

thank you

**Comment by CAMOBAP** [comment]
@ReesePlews I'm not sure that https://github.com/metanorma/chocolatey-metanorma/issues/76 can affect this it's an infrastructure issue that blocks `metanorma` install in GitHub Actions environment

Could you please report a separate issue for https://github.com/metanorma/metanorma-ieee/issues/new with details or provide technical details in the way you prefer
