### ISSUE TITLE
1.8.2 Release failure

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#312]
Observed issues:

1. "Invalid MathML" https://github.com/metanorma/packed-mn/actions/runs/6008410758
    Affected flavors: `bipm`, `itu`, `jcgm`
    Relevant issue: https://github.com/plurimath/plurimath/issues/183

1. And "`dig': String does not have #dig method (TypeError)" https://github.com/metanorma/metanorma-cli/actions/runs/6008320853/job/16298011674
    Affected flavors: `ietf` (rfc template)

P.S. Those issues was discovered in 1.8.2-pre release https://github.com/metanorma/packed-mn/actions/runs/5998894855/job/16268475936 but wasn't fixed for some reason...

P.S. This is "umbrella" ticket, once MathMl issue will be fixed we can restart release on `packed-mn`, `metnorma-docker` no new release of `metanorma-cli` will be need

cc @ronaldtse @opoudjis

**Comment by CAMOBAP** [comment]
"Invalid MathML:" still appears on: `bipm`,`itu`, `jcgm`. + `ogc` also 

The `packed-mn` was restarted and I can confirm that picked up latest:
 - `plurimath@0.4.3` -  https://github.com/metanorma/packed-mn/actions/runs/6008410758/job/16351790367#step:8:349
 - `isodoc@2.6.2` https://github.com/metanorma/packed-mn/actions/runs/6008410758/job/16351790367#step:8:542

@opoudjis maybe I missed something?

**Comment by ronaldtse** [comment]
@suleman-uzair can you please incorporate these MathML validation tests into Plurimath ASAP? They are blocking release. Thanks.

**Comment by opoudjis** [comment]
So... lemme get this straight:

https://github.com/metanorma/metanorma-cli/actions/runs/6091927992/job/16533805828 : now metanorma-cli goes through all the samples ever, and takes 4 hrs. On top of whatever docker is doing.

There is a reason I am constantly angry at this project. This is insane. 

Pending issues now:

1. template-ietf: https://github.com/metanorma/metanorma-ietf/issues/188, already addressed, planning to do hotfix of standoc
2. sample-bsi: missing images/coverpage.png
3. sample-nist claim that a URI is malformed (not seeing how).

We are going to introduce a fourth issue: I am going to review @suleman-uzair ’s latest Plurimath update, and switch html2doc across to using Plurimath. I am going to want to test it on all repos, to ensure we do not have even more disasters.

**Comment by CAMOBAP** [comment]
> https://github.com/metanorma/metanorma-cli/actions/runs/6091927992/job/16533805828 : now metanorma-cli goes through all the samples ever, and takes 4 hrs. On top of whatever docker is doing.

But what is the alternative?

Running tests locally cannot be an alternative because we must support macOS and Windows too

I suppose it better to spot issues here on `metanorma-cli` and spend this 4h before each release to not fall into the situation as with 1.8.2 never again, and only if metanorma-cli passed, we will initiate release docker/packend-mn etc.

I can handle releases starting from `metanorma-cli` and downstream, and leave it up to you how to manage/handle other gems releases and which strategy to use there

>  template-ietf: https://github.com/metanorma/metanorma-ietf/issues/188, already addressed, planning to do hotfix of standoc

Once it is released, to avoid any other regression for other flavors we have to rerun other flavors too, but for really straight cases we can just rerun failed flavors individually and wait less time

It looks like we discuss the same problem over and over again, from my point of view better to wait 4h and be sure that the same issues will not appear in packed-mn/docker/docker-private (3x time!)

But I'm open to any alternative till ti guarantee that `metanorma-cli` works proreply

**Comment by CAMOBAP** [comment]
https://github.com/metanorma/metanorma-cli/issues/312#issuecomment-1708056481 @ronaldtse any thoughts on this

**Comment by opoudjis** [comment]
I am going to delay the Plurimath testing on Github till next release, and test it locally first, enough has gone wrong already.

**Comment by opoudjis** [comment]
Standoc and NIST hotfixes release, and sample repos updated.

**Comment by CAMOBAP** [comment]
Observed issue in CI which doesn't allow release on experimental flavors fail, fixed, and restarted

**Comment by ronaldtse** [comment]
@CAMOBAP is there still an issue with release? Thanks.

**Comment by CAMOBAP** [comment]
> @CAMOBAP is there still an issue with release? Thanks.

yep( already fixed and restarted again

**Comment by CAMOBAP** [comment]
`metanorma-cli@1.8.3` released but `packed-mn`, `metanorma-docker` job wasn't triggered....

<img width="920" alt="Screenshot 2023-09-07 at 5 22 09 PM" src="https://github.com/metanorma/metanorma-cli/assets/2169738/6698a55b-c4d1-44fa-9161-37d04491e321">

Investigating what happens, right now

**Comment by CAMOBAP** [comment]
Fixed in https://github.com/metanorma/ci/commit/39a60ad9fe52d00f3beeb08dbb7e28f93e896b40

**Comment by CAMOBAP** [comment]
- metanorma-docker - [all images released](https://hub.docker.com/r/metanorma/metanorma/tags) 
- metanorma-snap - [released](https://snapcraft.io/metanorma)
- homebrew-metanorma - [released*](https://github.com/metanorma/homebrew-metanorma/releases/tag/v1.8.3) - CI hung, but tag is pushed and it's available to use 
- metanorma-chocolatey - failed because https://github.com/metanorma/chocolatey-metanorma/issues/76 happens again, last time it's gone after git.install update, to be investigated

I'm closing this issue and will continue work in the scope of https://github.com/metanorma/chocolatey-metanorma/issues/76

FYI @opoudjis @ronaldtse

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !
