### ISSUE TITLE
Inkscape errors blocking release on GHA

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cli#315]
https://github.com/metanorma/metanorma-cli/actions/runs/6612809719/job/17970391318

**Comment by ronaldtse** [comment]
@alexeymorozov is this something the latest Vectory GHA actions can fix?

**Comment by CAMOBAP** [comment]
Fixed in https://github.com/metanorma/ci/commit/a4b5a36de23e8dc813e1dcb1bef47886e7949a69, CI restarted

**Comment by ronaldtse** [comment]
@CAMOBAP could you help check this executable not found problem? Thanks.

**Comment by opoudjis** [comment]
Has gone away
