### ISSUE TITLE
Release blocked by fontist and github fetches

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cli#319]
https://github.com/metanorma/metanorma-cli/actions/runs/7459989544/job/20301295815
https://github.com/metanorma/metanorma-cli/actions/runs/7459989544/job/20301335188

And

https://github.com/metanorma/metanorma-cli/actions/runs/7459989544/job/20301543683
https://github.com/metanorma/metanorma-cli/actions/runs/7459989544/job/20301566006

**Comment by CAMOBAP** [comment]
Network issue, A simple re-run resolved the issue

Release workflow failed as expected because manual release of 1.9.0 https://github.com/metanorma/metanorma-cli/actions/runs/7464793647/job/20312535857
