### ISSUE TITLE
1.9.2 release failed

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#321]
- [x] metanorma-un | `undefined method `strip' for nil:NilClass` https://github.com/metanorma/metanorma-un/issues/226
- [x] metanorma-ietf | `Fatal: unable to generate txt, the command `xml2rfc` is not found in path.` https://github.com/metanorma/ci/commit/327abcb9205dec1137a51085a72a1a29d0e2d5cc
- [x] metanorma-ieee | `undefined method `previous=' for nil:NilClass`
- [x] ieee-private | `org.apache.fop.render.intermediate.IFException: I/O error flushing the PDF document`
- [x] metanorma-jcgm | `invalid index "see" cross-reference: wrong number of attributes in 'index:see[model,mathematical,of the measurement,measurement,mathematical model of the]'`

@opoudjis @ronaldtse it's hard for me to triage severity and importance of those issues let me know please

**Comment by opoudjis** [comment]
Resolved most of these

**Comment by opoudjis** [comment]
Of these:

* metanorma-un: resolved
* metanorma-ietf: that's an issue for you, @CAMOBAP . Seems to be (yet) another environment issue, this time with finding xml2rfc
* metanorma-ieee: resolved, same issue as for metanorma-un
* ieee-private: Reported as https://github.com/metanorma/metanorma-ieee/issues/347
* metanorma-jcgm: resolved in https://github.com/metanorma/mn-samples-jcgm/commit/cee216062bac7a005a3774117a077e7fa96e056b

**Comment by CAMOBAP** [comment]
@opoudjis thanks for update, just restarted workflow

**Comment by opoudjis** [comment]
Cool, I was about to myself. OK, we'll see what happens...

**Comment by CAMOBAP** [comment]
gem 1.9.2 is released
