### ISSUE TITLE
CLI: `--no-no-install-fonts` looks ugly replace it with `--install-fonts` with default to false

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#322]
### Intro

Recently I faced with issue that metanorma-cli didn't installed required front "Work Sans Medium" https://github.com/metanorma/packed-mn/issues/225

### Workaround

call `metanorma` with `--no-no-install-fonts` flag

### Problem

`--no-no-install-fonts` looks ugly and better to replace it with `install-fonts` with default value `true` as was originally expected

cc @opoudjis  @ronaldtse any thoughts

**Comment by opoudjis** [comment]
OK by me. We're presumably not disrupting too much usage with this, but retain the original --no-no-install-flags for backward compatibility just in case?

**Comment by ronaldtse** [comment]
`--no-no-install-fonts` => ugly... I don't think anyone is using it? Let's just rename it.

**Comment by ReesePlews** [comment]
this is causing github generate jobs to fail across all repos.

```
Run cd .
ERROR: "metanorma site generate" was called with arguments [".", "--no-no-install-fonts"]
Usage: "metanorma site generate [SOURCE_PATH]"
Error: Process completed with exit code 1.
```

please provide a work around for how to fix this on github.  thank you.

**Comment by ronaldtse** [comment]
@CAMOBAP can you help check the GitHub actions?

**Comment by ronaldtse** [comment]
The GitHub actions that affect this must be here:
* https://github.com/search?q=org%3Aactions-mn%20install-fonts&type=code

I suspect they are:

* https://github.com/actions-mn/compile/blob/6a1476c1528942e0a57ceb2d2fc08ec40585da23/action.yml#L42
* https://github.com/actions-mn/docker-cli/blob/a52ea0ce020b311e76d4da89a09010c935177772/site-gen/action.yml#L16
* https://github.com/actions-mn/cli/blob/d99ce6b2f8aaa386605ff3855bafa48c16ad67a2/collection/action.yml#L19

**Comment by CAMOBAP** [comment]
@ReesePlews to be on the same page which actions from actions-mn you are using?

**Comment by ReesePlews** [comment]
hi @CAMOBAP thanks for looking into this. i have confirmed you have access to the two projects listed below.

one repo is here
https://github.com/metanorma/iso-19135/actions/runs/9377121970/job/25818161033

the other is here
https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/actions/runs/9370557418

where are these actions mentioned? are they "per repository" or "something managed by metanorma"? no files to generate the document were edited so i really dont know where they are coming from.   

if you need something else, please let me know.  thanks

**Comment by ronaldtse** [comment]
Both repos uses the build-and-publish workflow:
* https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/actions/runs/9370557418/workflow (v1)
* https://github.com/metanorma/iso-19135/actions/runs/9377121970/workflow (main)

So we have to create an update to the `v1` tag for build-and-publish.

**Comment by ReesePlews** [comment]
hi @ronaldtse thanks for the info, i looked at the workflows in those repos before adding the issues and i could not find the --no-no-install-fonts as a command parameter. that must be in the "build-and-publish" script. is that something each project controls or are they under metanorma control (on github, or in the instance)?

**Comment by ReesePlews** [comment]
solution to fix this issue related to the `build-and-publish` workflow was discussed [here](https://github.com/metanorma/metanorma-ieee/issues/376);

i dont quite understand how the changes surrounding the `--no-no-install-fonts` issue was related to the build-and-publish issue mentioned above. but a manual update to `v2 `in the `generate.yml` file in one of the repos solved the problem. the other repo was already using `main `in the `generate.yml` file, and seemed to be corrected without any revision the next time the document was generated.

thank you for helping to get this fixed.

**Comment by ronaldtse** [comment]
This is done, closing.
