### ISSUE TITLE
(URGENT) Automatically add `rxl` output extension when using `site generate` command

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#323]
From @opoudjis:

Easier to flow through, and RXL are useful metadata. I will see if I can add `rxl` to the outputs in case there is site compilation; we already implicitly add `presentation` to the outputs if there is html, doc, pdf involved. That way, you will not need to remember to specity rxl.

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-ogc/issues/644#issuecomment-2001111647_

**Comment by ronaldtse** [comment]
@opoudjis do you think you can handle this? Thanks!

**Comment by opoudjis** [comment]
Not to raise expectations, since I'm not familiar with metanorma-cli, but this is turning out to be straightforward...

**Comment by ronaldtse** [comment]
Thank you @opoudjis !
