### ISSUE TITLE
PDF process: command-line change to mn2pdf stack and heap space

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#326]
We need to expose the thread stack and heap space memory limits of mn2pdf for conditions like this:
* https://github.com/metanorma/iso-2533/issues/20

Where the 2GB limit to heap space does not allow PDF generation to complete.

I propose that we use something like:
```
--java-heap-min {defaults to 512m}
--java-heap-max {defaults to 2g}
--java-threadstack-max {defaults to 5m}
```

And this goes into the mn2pdf-ruby library as well.

Depends on:
* [x] https://github.com/metanorma/mn2pdf-ruby/issues/39

**Comment by Intelligent2013** [comment]
From https://github.com/metanorma/iso-2533/issues/20:
> We need to document when additional heap space is needed too.

**Comment by CAMOBAP** [comment]
@ronaldtse I propose another solution https://github.com/metanorma/mn2pdf-ruby/issues/39#issuecomment-2269136854

Any feedback appreciated

**Comment by CAMOBAP** [comment]
Implemented via JAVA_OPTS env var
