### ISSUE TITLE
URGENT: Implement integration testing on Metanorma stack

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cli#330]
For months now, every single release of Metanorma has been foiled by integration issues, and held up for days. Some of these have arisen from Github Actions environment configuration. Some of these have arisen from dependencies on other parts of the stack, including Fontist, Relaton, Plurimath, and Vectory.

The release process already takes the better part of six hours just to clear metanorma-cli. To have to deal every single release with these integration issues, on top of the burden of internal testing, is simply unworkable and broken, and it is an ongoing unmanaged reputational risk for Ribose. It is also an unmanaged reputational risk for me personally, as I am managing the Metanorma stack, and I am the only developer visible to external clients.

At issue is the need for integration testing, which needs to be happening well in advance of the release, so that issues can be identified and rectified well in advance of me running into them on release day. I should not be the one finding the integration issues, as I am not the one that can do anything about them. And our external—and paying—clients should not be seeing the results of us not identifying integration issues in advance of the release.

The following needs to be done going forward. Until it is, releases are a waste of everyone's time scrambling after the event, and I am not inclined to continue with them.

* Integration testing needs to occur at minimum once every fortnight, alternating with the release itself; it would be preferable for it to occur once every day or two.
* Integration testing needs to involve those Metanorma repositories which have the most external dependencies. For Github Actions, and for external gems, that means isodoc, metanorma-standoc, and metanorma-iso. (The latter has fewer dependencies, but they critically include Fontist.)
* There is no need for integration testing to include samples repositories, nor metanorma-cli. Samples repositories take multple hours to run, and will not expose substantially more than the nominated repositories already do. The one dependency they do expose is Plurimath, because of the broad range of mathematical formulae they contain; but this integration testing has already been realised recently between Plurimath and metanorma-cli
* The integration testing does not need to include every Ruby environment we support, and it should not be allowed to run for hours. If there is an integration breakage, it only needs to break once for us to realise there is an issue. I request that integration testing be done on the latest supported version of Ruby, 3,3, but for each of the OS's we support in Github Actions testing: MacOS, Linux, and Windows. 
* The integration testing should only involve released gems, and not current development branches. It is only integration testing with external software; the internal dependency tracking within Metanorma is time-consuming enough, without replicating it here.
* The results of integration testing will need to be monitored by an integration manager, who will identify which breakages result from integration issues, and raise the concern with the maintainer responsible, where applicable.

**Comment by CAMOBAP** [comment]
ping @opoudjis

**Comment by opoudjis** [comment]
> > There is no need for integration testing to include samples repositories, nor metanorma-cli
> It's a big surprise for me. As far as I remember the original ticket was created by @ronaldtse, for me (as a person who doesn't understand the product as well as @opoudjis ) it seems a good place to do it. But if it's not good decision let's reject it and save enough of waiting time for ci

As you surmised at the end, there are two different kinds of testing.

* The integration testing to be done every 1-2 days is in my opinion a smoke test, to confirm that none of the dependencies has broken. It needs to run reasonably quickly, and not tie up GHA resources. For that reason, I think it needs to exclude samples
* The testing of all samples repos still needs to happen on release of metanorma-cli, and it needs to include all samples, as it currently does.

@ronaldtse has the final say, but I do not think dependencies testing needs to include samples repos.


> > The integration testing should only involve released gems, and not current development branches. It is only integration testing with external software; the internal dependency tracking within Metanorma is time-consuming enough, without replicating it here.
> 
> Does it mean that we do release and then test? In this case, should we call it post-release testing to make it clear?

This is not continuous integration testing, and given all the dependencies between metanorma gems, I don't want to move to immediate releases: this is indeed intended as post-release testing.


> > The results of integration testing will need to be monitored by an integration manager, who will identify which breakages result from integration issues, and raise the concern with the maintainer responsible, where applicable.
> 
> Just to be on the same page, we are calling "integration testing" running `rspec` once in 1-2 days for `isodoc`, `metanorma-standoc`, and `metanorma-iso` repositories, did I get it right?

Yes. If it helps to call it post-release testing or smoke testing, then let's do that.

**Comment by CAMOBAP** [comment]
@opoudjis thanks for the answers, I will add cron testing for those repositories

One more question @opoudjis does it make sense for ci to create an issue automatically once this ci fails for this daily test runs?

**Comment by CAMOBAP** [comment]
Integration workflow added:
- https://github.com/metanorma/isodoc/actions/workflows/integration.yml
- https://github.com/metanorma/metanorma-iso/actions/workflows/integration.yml
- https://github.com/metanorma/metanorma-standoc/actions/workflows/integration.yml

@opoudjis please share your vision on other repos that make sense to add. Because if we need add more than 20-15 repos I have to think about cron condition 'distribution' to not start all integration at one time, for ~10 repos it will be ok to have the same time

**Comment by opoudjis** [comment]
> @opoudjis thanks for the answers, I will add cron testing for those repositories
> 
> One more question @opoudjis does it make sense for ci to create an issue automatically once this ci fails for this daily test runs?

It depends on who will be processing those issues lol... but yeah, it is a matter of traceability. I don't like the prospect of being deluged by tickets, but they will be problems that need to be assigned to people to address.

**Comment by opoudjis** [comment]
> Integration workflow added:
> 
> * https://github.com/metanorma/isodoc/actions/workflows/integration.yml
> * https://github.com/metanorma/metanorma-iso/actions/workflows/integration.yml
> * https://github.com/metanorma/metanorma-standoc/actions/workflows/integration.yml
> 
> @opoudjis please share your vision on other repos that make sense to add. Because if we need add more than 20-15 repos I have to think about cron condition 'distribution' to not start all integration at one time, for ~10 repos it will be ok to have the same time

As I already said, I don't want this integration testing to be a replica of the release testing we do in metanorma-cli, and I think it would be counterproductive to extend it past these three gems. The rest do not have serious external dependency issues, they're all in those three gems.
