### ISSUE TITLE
Update Ruby version

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cli#331]
It already being June, we need to:

* Drop all support in GHA jobs for Ruby 2.7 and 3.0
* Drop all support in Rubocop for Ruby 2.7 and 3.0 (if not done already)
* Support Ruby 3.4 in GHA
* Support Ruby 3.4 in Rubocop

Given how time consuming running GHA is, we should be considering supporting only three versions of Ruby in Metanorma, and not four as is currently the case.

**Comment by CAMOBAP** [comment]
@opoudjis to be on the same page "Support Ruby 3.4 in Rubocop" mean that we use 

```
AllCops:
  TargetRubyVersion: 3.4
```

right?

**Comment by opoudjis** [comment]
> @opoudjis to be on the same page "Support Ruby 3.4 in Rubocop" mean that we use
> 
> ```
> AllCops:
>   TargetRubyVersion: 3.4
> ```
> 
> right?

When we adopt 3.4, yes.

**Comment by CAMOBAP** [comment]
Done
