### ISSUE TITLE
metanorma executable reported missing on GHA

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cli#332]
https://github.com/metanorma/metanorma-cli/actions/runs/9552082732/job/26342384696

Preventing release. Have rerun job, same result.

**Comment by CAMOBAP** [comment]
Fixed, I will rerun ASAP

**Comment by CAMOBAP** [comment]
One more issue was discovered https://github.com/metanorma/mn2pdf/issues/253
@Intelligent2013 could you please have a look

**Comment by CAMOBAP** [comment]
Done
