### ISSUE TITLE
Refactor CLI to use Thor

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#34]
We want to use the same command framework (Thor) as Relaton CLI.

**Comment by abunashir** [comment]
It's your lucky day Ron 🕺, I'm already on it https://github.com/metanorma/metanorma-cli/pull/36 :)

**Comment by ronaldtse** [comment]
Thanks @abunashir !

**Comment by abunashir** [comment]
@ronaldtse, @opoudjis: I'm migrating our current `exe/metanorma` to thor based solution, so we can easily add any other commands to the same interface and also use other benefits of it. But there is  problem with the current executable, we are currently using it as root interface which is making it bit harder to hook the other sub-command to it.

For a CLI tool is't usual to show the help documentation if the executable is called without any argument, and I was thinking to do the same for this interface, it will make also save me from some additinal work around.

So what do you think about putting this parsing / generation behavior to under a new subcommand like `metanorma generate` or something?

**Comment by ronaldtse** [comment]
Finally found this issue :-)

1. Yes we want to use Thor.
2. Yes we can put under a sub command. However, we want to assume the root command is the “generate” or “compile” so that it adheres to current convention. I believe this should be doable under the Thor framework. 
3. We want a help command (currently under -h) such as `metanorma help`).

**Comment by abunashir** [comment]
It's done, @ronaldtse can we close this one or you want me to add something else there?

**Comment by ronaldtse** [comment]
Thanks @abunashir , closing.
