### ISSUE TITLE
mn2pdf old version in metanorma.exe

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-cli#344]
I've installed the latest Metanorma via Chocolatey by (https://www.metanorma.org/install/windows/):
> choco install metanorma -y

And tried to generate the PDF. The generated PDF  has the 'PDF producer version' mn2pdf v1.99:
![image](https://github.com/user-attachments/assets/0cfe4b3c-8fe3-4f5f-8759-b700a803c473)

Another method to check: when I just run the `metanorma.exe` from path `C:\ProgramData\chocolatey\lib\metanorma\tools\metanorma.exe`, it unpacks the files into the temp folder like this:
```
C:\Documents and Settings\TestUser\Local Settings\Temp\aibCFE.tmp
```
And you can see the folder `mn2pdf-1.99` in the folder `C:\Documents and Settings\IntlUser\Local Settings\Temp\aibCFE.tmp\lib\ruby\gems\3.1.0\gems\`

Metanorma 1.10.10 released last week (14 - 15 Oct)

mn2pdf [v2.04](https://github.com/metanorma/mn2pdf/releases/tag/v2.04) released 2 weeks ago.
mn2pdf [v1.99](https://github.com/metanorma/mn2pdf/releases/tag/v1.99) released Sep 9.

It means that metanorma should contain mn2pdf v2.04 .

**Comment by CAMOBAP** [comment]
- https://github.com/metanorma/metanorma/pull/428
