### ISSUE TITLE
Maybe ... `metanorma-cli` does not depend on the installation of `metanorma`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#37]
Think about it. Installation of metanorma is quite complex and requires development rights on the machine.

* If the user already has metanorma installed, there's no need to run compilation on the remote end.
 
* For example, without metanorma installed, the user can still run `metanorma new -t iso -d standard my-standard`, then `metanorma compile my-standard`. I think we need some YAML config file in the my-standard directory for this.

**Comment by opoudjis** [comment]
... You've asked me to comment on this, @ronaldtse, but this truly makes no sense to me at all.

* All metanorma-cli does is gather up some command line options, and pass them and a file name on to the metanorma gem. Of course it depends on the metanorma gem.
* What you might be referring to instead is the installation of the Metanorma environment. And of course you're not going to be able to compile jack without the Metanorma environment in place.

I don't know what you're referring to with remote end, and I don't know how you expect `metanorma compile my-standard` to do anything meaningful without all that stuff installed on the local machine.

Please try again? What am I missing?

**Comment by ronaldtse** [comment]
Imagine there is a command called `metanorma-remote`. It compiles everything remotely. This command does not rely on a local metanorma environment -- it is only a pure Ruby wrapper.

Everything it does is sent to a remote endpoint that can execute them.

**Comment by opoudjis** [comment]
It's still a command line. I don't see the attraction. If you can use a command line, it's not *that* difficult to install metanorma; the number of people who will want to run metanorma remotely, and will not want to use a Web UI, can't be big enough to bother supporting.

**Comment by ronaldtse** [comment]
Closing this in favor of #156
