### ISSUE TITLE
Make release

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#46]
As title. For @opoudjis

**Comment by opoudjis** [comment]
OK, I will do global release of gems now.

**Comment by opoudjis** [comment]
@abunashir, I invite you to write more detailed release notes on https://github.com/metanorma/metanorma-cli/releases/tag/v1.1.7

**Comment by ronaldtse** [comment]
Done, thanks!

**Comment by opoudjis** [comment]
... Not seeing any edits on the release; where did you put them?

**Comment by ronaldtse** [comment]
Did not add any. Didn't realize you left this for @abunashir .

**Comment by abunashir** [comment]
@opoudjis I've updated the release notes, thanks! Should we also maintain a changelog whenever we are doing a version bump in the future?

**Comment by opoudjis** [comment]
I've been copying your annotations on pull requests until now.  I've been using tickets to assemble my release notes, but you can do whatever works for you - as long as I can find it.

**Comment by abunashir** [comment]
I was thinking more likely to commit the changelog with the repo - like this one here https://github.com/bundler/bundler/blob/master/CHANGELOG.md.

Whenever someone is adding a new feature, updating something that could fix a potential issue or add some breaking changes then let's also suggest them to update the changelog.

I hope this will save you some time, and also anyone else going through the codebase can instantly get an overview of all the changes.

**Comment by opoudjis** [comment]
I have been annotating releases on all github releases I manage. If you want to do things that way, you can, but that's not how I'm managing the 50-odd gems I'm responsible for, and we have not discussed a Metanorma-wide approach to change logs.
