### ISSUE TITLE
Spurious warning on "not a default standard type"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#48]
When running the CLI, this always shows up regardless of type specified.

```
[metanorma] Warning: ogc is not a default standard type.
[metanorma] Info: Attempting to load `metanorma-ogc` gem for standard type `ogc`.
```

This is no longer accurate because all standard gems are now loaded on demand. Previously this message indicated the loading of a custom gem.

How about we just remove this line?
```
[metanorma] Warning: ogc is not a default standard type.
```

Change
```
[metanorma] Info: Attempting to load `metanorma-ogc` gem for standard type `ogc`.
```
to
```
[metanorma] Info: Loading `metanorma-ogc` gem for standard type `ogc`.
```

**Comment by abunashir** [comment]
@ronaldtse This one is coming from [metanorma/compile.rb#L54](https://github.com/metanorma/metanorma/blob/master/lib/metanorma/compile.rb#L54). Ideally, I would say we should also consider putting those debugging messages under a configuration or something.

cc: @opoudjis

**Comment by ronaldtse** [comment]
Yes, please help proceed @abunashir . In this case please also setup debug mode with different levels of messages. Thanks!
