### ISSUE TITLE
-r not working in new release

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-cli#49]
`metanorma -t ogc -r metanorma-ogc test.adoc` does not work. Please address.

I have not put the setenv on for the new interface. Since `metanorma -t ogc test.adoc` does work, that's not the issue.

**Comment by ronaldtse** [comment]
@abunashir you need to port:

https://github.com/metanorma/metanorma-cli/blob/master/exe/metanorma#L67-L74

to this file:

**Comment by ronaldtse** [comment]
And I also found the overloading of `-r` here (https://github.com/metanorma/metanorma-cli/blob/23d43a944dbfd8013866f02551b8dfd4f6e2011d/lib/metanorma/cli/command.rb#L12) disturbing. Can we use another switch for "overwriting"?

**Comment by abunashir** [comment]
@opoudjis, @ronaldtse: This issue should be resolved in the attached PR, please have a look and feel free to merge is it, thanks!

FYI, @ronaldtse  this also updates the `overwrite` options to be a straight forward flag!

**Comment by opoudjis** [comment]
I have no particular problem with the PR, but... wouldn't you want to give a one letter option to overwrite too? Since -r is taken, what about -R?

**Comment by abunashir** [comment]
Yap, we could do that, but since `-r` is already used, so instead of using the capital letter, what about we use `-y` (most of the tool use this to confirm with a message - similar to our case)?

> I have no particular problem with the PR, but... wouldn't you want to give a one letter option to overwrite too? Since -r is taken, what about -R?

**Comment by ronaldtse** [comment]
I am uneasy with `-r` being overwriting -- maybe `-f` (force) would be better?

**Comment by abunashir** [comment]
@ronaldtse In the other interface, we are using `-f` to specify the format and I think we should try to keep some consistency throughout the CLI, so I went with `y`, Are you okay with that or you would prefer it to be changed to `-f'`?

> I am uneasy with `-r` being overwriting -- maybe `-f` (force) would be better?

**Comment by ronaldtse** [comment]
Oh... `-f` is not currently used because we only support one type of input. It might change soon, but we can change the input format to use any other option argument. Any suggestion?

**Comment by opoudjis** [comment]
@ronaldtse, @abunashir ended up using -y. It's an arbitrary choice, and that's ok.

**Comment by ronaldtse** [comment]
@opoudjis fine, and we need to be sure we actually ask questions if we don't have `-y`, otherwise it breaks the convention.

**Comment by abunashir** [comment]
@ronaldtse: Yap, we are asking the question here: https://github.com/metanorma/metanorma-cli/blob/master/lib/metanorma/cli/generator.rb#L125, and initially I added it to skip this question for our test suite
