### ISSUE TITLE
Bug: `metanorma new` does not copy dot-files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#51]
In the `mn-templates-csd` template repository, the `common/` directory provides a number of dot-files, including:

* `.gitignore`
* `.gitlab-ci.yml`
* `.travis.yml`

However, today the `metanorma new` command does not copy them from `common`.

Example:

```sh
bundle exec metanorma new my-new-document -t ogc -d standard
Creating my-new-document/Makefile
Creating my-new-document/appveyor.yml
Creating my-new-document/Gemfile
Creating my-new-document/deploy.sh
Creating my-new-document/Makefile.win
Creating my-new-document/sections/clause_7_normative_text.adoc
Creating my-new-document/sections/clause_3_references.adoc
Creating my-new-document/sections/annex-a.adoc
Creating my-new-document/sections/annex-bibliography.adoc
Creating my-new-document/sections/clause_2_conformance.adoc
Creating my-new-document/sections/clause_0_front_material.adoc
Creating my-new-document/sections/clause_8_media_types.adoc
Creating my-new-document/sections/annex-history.adoc
Creating my-new-document/sections/annex-n.adoc
Creating my-new-document/sections/clause_5_conventions.adoc
Creating my-new-document/sections/clause_6_informative_text.adoc
Creating my-new-document/sections/clause_1_scope.adoc
Creating my-new-document/sections/clause_4_terms_and_definitions.adoc
Creating my-new-document/UML/README.adoc
Creating my-new-document/images/README.adoc
Creating my-new-document/abstract_tests/README.adoc
Creating my-new-document/code/README.adoc
Creating my-new-document/requirements/requirement.adoc
Creating my-new-document/requirements/README.adoc
Creating my-new-document/requirements/requirements_class.adoc
Creating my-new-document/README.adoc
Creating my-new-document/document.adoc
Creating my-new-document/figures/README.adoc
```

@abunashir could you fix this ASAP? Thanks.

**Comment by abunashir** [comment]
Hi @ronaldtse we aren't copying the common files from each of the templates. Since we were duplicating the same common files in each of the templates, and in my primary investigation it looked exactly the same except (some standard specific gitignore), so that's why I moved those the `templates/base` folder under this CLI.

So, when ever we are generating a new document then this base templates + custom type specific templates are used. But you are right, we didn't include this dot file in the base template.

I will do it now, hopefully, this will resolve the issues?

**Comment by ronaldtse** [comment]
Yes please do so, thanks @abunashir !

**Comment by ronaldtse** [comment]
Will we be able to make a new release for this since the blog post is going out? 

https://github.com/metanorma/metanorma.com/pull/82

**Comment by abunashir** [comment]
I've pushed some changes and once merged then it should fix this issue. Btw, once merged let's also remove those common files for each separate template and only use the `templates/base` directory in this repo for all common templates. What do you think @ronaldtse ?

**Comment by ronaldtse** [comment]
Yes please.
