### ISSUE TITLE
Improve `metanorma help`

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-cli#56]
### Intro / Problem

For v1.1.7 our `metanorma help` looks like this

```
Commands:
  metanorma compile FILENAME                                # Compile to a metanorma document
  metanorma help [COMMAND]                                  # Describe available commands or one specific command
  metanorma new NAME -d, --doctype=DOCTYPE -t, --type=TYPE  # Create new Metanorma document
  metanorma version -t, --type=TYPE                         # Version of the code
```

I see a list of problems here:
 - No general description
 - No usage pattern
 - Not standardized action description (actions are compile, help, new, version)
 - No list of valid/accepted values especially for `--type` & `--doctype`
 - Poor error handling, just type wrong command name & it will print stack trace which doesn't clarify the problem

### Proposed solution

Let's use https://ruby-doc.org/stdlib-2.4.1/libdoc/optparse/rdoc/OptionParser.html standard module which will fix most of the issues, we will be able even to implement guess like in the git command

```
git sats
git: 'sats' is not a git command. See 'git --help'.

The most similar command is
	stash
```

cc @ronaldtse @abunashir

**Comment by ronaldtse** [comment]
@abunashir we actually migrated to using Thor to handle our commands, previously we used OptionParser. Do you have a way of achieve the said solutions through Thor? 


I think these can be done using Thor
* No general description
* No usage pattern
* Not standardized action description (actions are compile, help, new, version)

This is due to our current gem loading strategy which is load-on-demand. We need to allow load the schema (the RNG file) but without `require`ing the full gem.
* No list of valid/accepted values especially for --type & --doctype

This is handleable using/through Thor:
* Poor error handling, just type wrong command name & it will print stack trace which doesn't clarify the problem

**Comment by CAMOBAP795** [comment]
> we actually migrated to using Thor to handle our commands

My bad, I missed this, BTW why we use Thor instead OptionParser?

**Comment by ronaldtse** [comment]
Because Thor allowed us to establish a clean framework for commands (2nd level commands) in the `git` style. In our experience we found it much easier to maintain in the long run.

**Comment by abunashir** [comment]
@ronaldtse, @CAMOBAP795 This is the default in build `help` format coming out of Thor, and used by most of the ruby based CLI. By default, the `help` command will describe the high-level commands, and if you want to find out the details for any command then you can use the `help [command_name]` and it will display the details with usages pattern. For example:

<img width="973" alt="Screenshot 2019-04-29 14 28 16" src="https://user-images.githubusercontent.com/1220911/56896221-71937b80-6a8b-11e9-8cc3-47e9ec242eb2.png">

Is it something you meant by general description and use pattern in your comment? Or you meant having a `man` pages for these commands?

**Comment by CAMOBAP795** [comment]
@abunashir my original idea that it will be nice if `metanorma help new` will contain possible values for  `--type` & `--doctype`, how do you think about this?

**Comment by abunashir** [comment]
@ronaldtse: I agree on this one, but as I mentioned to you earlier, loading those libraries upfront was solving this problem, but then it was making the whole CLI  supper slow, so I would say, until we have some optimized solution for this probably we can keep this one as a pending enhancement and describe that in the documentation.


> * No list of valid/accepted values especially for --type & --doctype
>

**Comment by abunashir** [comment]
I agree on this one, recently I did some update, so it shouldn't fail that easily anymore, instead say it out loud that that's probably an invalid file or command. But let me know if want me to add anything else there.

> * Poor error handling, just type wrong command name & it will print stack trace which doesn't clarify the problem

**Comment by CAMOBAP795** [comment]
> I agree on this one, recently I did some update, so it shouldn't fail that easily anymore, instead say it out loud that that's probably an invalid file or command. But let me know if want me to add anything else there.

@abunashir  I think it will be enough, is it committed already?

**Comment by abunashir** [comment]
Yes, it was done here #55, but I don't think it was released in RubyGems yet.

> @abunashir I think it will be enough, is it committed already?

**Comment by abunashir** [comment]
We could have done that, but we would need to customize quite some stuff on setup, and also from my personal experience when you have an example with real value then the user is tempted to just copy and paste that command.

So, I actually like this way, in this case the user has some reference but not real value, so it kind of indication that they need to write it as necessary for their and maybe have some sort of man document later that could provide much more detail information. cc: @CAMOBAP795 

> @abunashir my original idea that it will be nice if `metanorma help new` will contain possible values for `--type` & `--doctype`, how do you think about this?

**Comment by ronaldtse** [comment]
> @ronaldtse: I agree on this one, but as I mentioned to you earlier, loading those libraries upfront was solving this problem, but then it was making the whole CLI supper slow, so I would say, until we have some optimized solution for this probably we can keep this one as a pending enhancement and describe that in the documentation.

Then can we do something like `metanorma list-doctypes  iso` to list out `iso` doctypes?

**Comment by ronaldtse** [comment]
We already have the types documented in metanorma.com, but it's really annoying to keep look for that when the types are provided in the gems already.

**Comment by abunashir** [comment]
Actually, I was thinking the same, have a separate command, and we can even invoke that automatically if metnorma raise an exception for invalid type 🕺

> Then can we do something like `metanorma list-doctypes iso` to list out `iso` doctypes?

**Comment by ronaldtse** [comment]
Agree!

**Comment by abunashir** [comment]
This should be resolved now, should we close this one? @CAMOBAP795, @ronaldtse

**Comment by ronaldtse** [comment]
Yup, thanks @abunashir !
