### ISSUE TITLE
Update base templates (current Travis one not working)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#60]
Use this travis config:
* https://github.com/metanorma/csa-caiq/blob/master/.travis.yml

Use this Makefile:
* https://github.com/metanorma/csa-caiq/blob/master/Makefile

Use this gitignore:
* https://github.com/metanorma/csa-caiq/blob/master/.gitignore

Remove `deploy.sh` (the Travis script uses https://github.com/metanorma/metanorma-build-scripts/blob/master/deploy-to-gh-pages.sh)

**Comment by ronaldtse** [comment]
@abunashir this is rather urgent. Thanks!

**Comment by abunashir** [comment]
@ronaldtse done in the attached PR, please check it out!
