### ISSUE TITLE
Update `Makefile.win` to mirror updated `Makefile`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#61]
@CAMOBAP795 could you please help update `Makefile.win` to reflect the current `Makefile`?

1. There is no more `metanorma.env` file. The output formats are read via:
https://github.com/metanorma/csa-caiq/blob/c17534c929ff250cca6ed8dd127c60b078443a75/Makefile#L4-L5

2. The targets to decrypt deploy key are now removed (functionality moved to metanorma-build-scripts/deploy-to-gh-pages.sh)

https://github.com/metanorma/csa-caiq/blob/c17534c929ff250cca6ed8dd127c60b078443a75/Makefile#L119-L126

And please make sure it is compilable using `Makefile.win`.

Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse should this be done for https://github.com/metanorma/unece-cefact-recommendation-42/blob/master/Makefile.win and https://github.com/metanorma/ogc-tcpnp/blob/master/Makefile.win too?

**Comment by ronaldtse** [comment]
Yes, of course. To all the repos that have Makefile.win. Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse 3 PRs ready for review
 - #67 
 - https://github.com/metanorma/ogc-tcpnp/pull/6
 - https://github.com/metanorma/unece-cefact-recommendation-42/pull/6

OSX some OSX builds blocked by https://github.com/metanorma/metanorma-standoc/issues/69

**Comment by ronaldtse** [comment]
All done, thanks @CAMOBAP795 !
