### ISSUE TITLE
Metanorma don't return non zero exit code on failure

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-cli#74]
I faced with this during https://travis-ci.com/metanorma/mn-templates-iso/jobs/199659544 https://ci.appveyor.com/project/ribose/mn-templates-iso/builds/24506334

metanorma command failed but CI pipeline is green because zero code was returned

@ronaldtse @abunashir please triage this, I can help with this if need

**Comment by abunashir** [comment]
@CAMOBAP795: Yap, my bad, I apparently did not return the correct status code for this one, I will update this one right away :) Thanks!

**Comment by abunashir** [comment]
@CAMOBAP795: This should be fixed in the attached PR, could you please double check and possibly merge it if that fixes the issue?
