### ISSUE TITLE
URGENT: Display possible extensions per standard type

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#76]
> `metanorma --type ietf -x xmlrfc cc-51006.adoc`
> What's this?
> `[metanorma] Error: xmlrfc format is not supported for this standard.`

We need to return the list of possible extensions to generate. It was previously in the CLI but now taken out to skip loading of gems.

> `[metanorma] Error: xmlrfc format is not supported for this standard.`

We need to show a list of valid extensions.

This is urgent. @abunashir can you please help? Thanks!

**Comment by abunashir** [comment]
@ronaldtse: This one should e resolved in the attached PR, could you please check and merge if you are happy with it?
