### ISSUE TITLE
Add command to list ALL supported extensions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#78]
I really don't think including 10 metanorma-* gems will cause loading to be slow. 

There must be something we're doing wrong in that require tree or in gem enumeration?

```
# To list all extensions for all flavors on this computer.
metanorma list-extensions
```

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-cli/pull/77#issuecomment-493138992_

**Comment by abunashir** [comment]
@ronaldtse: This should be resolved in the attached PR!
