### ISSUE TITLE
Adopt Makefile/travis from https://github.com/CalConnect/csd-vpoll

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#79]
The Makefile and travis.yml there supports IETF documents too. Should we port them over?

**Comment by abunashir** [comment]
@ronaldtse: Is this still relevant?

**Comment by ronaldtse** [comment]
@abunashir yes, it is still relevant. We don't want external Makefiles but want to include the functionality within the CLI (Metanorma CLI or Relaton CLI).

**Comment by abunashir** [comment]
@ronaldtse: What are the requirements here? Can you describe what exactly we want to achieve by this?

**Comment by abunashir** [comment]
@ronaldtse: This should be resolved the `metanorma site generate` right?

**Comment by ronaldtse** [comment]
@abunashir yes I believe so. Could you help make a PR that replaces the Makefile and update the GHA there? Thanks!

**Comment by abunashir** [comment]
We can close this one, once this is - https://github.com/metanorma/metanorma-build-scripts/pull/55 merged!

**Comment by ronaldtse** [comment]
Closed, thanks!
