### ISSUE TITLE
No way to get metarnorma-cli version

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-cli#85]
It will be nice if `metarnorma version`command will return `metarnorma-cli`'s version, because for now, it works only with `-t` param like `metanorma version -t iso`

cc @ronaldtse

**Comment by opoudjis** [comment]
That's logically asking for a different thing: the version of metanorma-cli (or, more correctly, of the metanorma gem), vs the version of the metanorma flavour gem.

**Comment by CAMOBAP795** [comment]
I think it's will be useful for troubleshooting, and `metanorma version` may return both `$metanorma-cli-gem-version / $metanorma-gem-version` (or by using another separator)

@opoudjis how do you think?

**Comment by ronaldtse** [comment]
I agree. There are other CLI that offer multiple version numbers, such as gpg .

**Comment by opoudjis** [comment]
I agree too.
