### ISSUE TITLE
`metanorma compile ...` path handling issues on windows

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#88]
`metanorma compile ... path` handling issues on windows. This is from https://github.com/metanorma/metanorma-ogc/issues/36#issuecomment-498020490 . 

For @CAMOBAP795

**Comment by CAMOBAP795** [comment]
Looks like a problem with this line https://github.com/metanorma/metanorma/blob/master/lib/metanorma/output/pdf.rb#L7-L8

Working on unit tests

**Comment by CAMOBAP795** [comment]
Done
