### ISSUE TITLE
`metanorma compile ... path` don't return non-zero exit code in case of error

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#89]
`metanorma compile ... path` don't return non-zero exit code in case of error. This is from https://github.com/metanorma/metanorma-ogc/issues/36#issuecomment-498020490 . 

For @CAMOBAP795

**Comment by CAMOBAP795** [comment]
Looks like for missing file case it's already done so I just added unit test for this & PR for throw error if puppeteer step failed https://github.com/metanorma/metanorma/pull/65

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Comment by CAMOBAP795** [comment]
Done
